### ISSUE TITLE
Make external image loading optional

### ISSUE THREAD

**Issue by HookedBehemoth** [rust-skia/rust-skia#1003]
I tried a library which used skia-safe and I was surprised to find that it pulls in ureq for a seemingly niche feature in the svg loader. Do you think you could make this part optional even when building with the svg feature?
I believe such an external asset loading should be handed back to the caller to decide what to do with it. With the current implementation authorization on the requested assets isn't possible either.

I'd be happy to provide a patch myself if you could tell me how you want it to be implemented.

https://github.com/rust-skia/rust-skia/blob/aa8c37c3e718c3df4ad28678f244d02490484095/skia-safe/src/modules/svg.rs#L122-L148

**Comment by Greatness7** [comment]
I've noticed that `ureq` and the dependencies it brings (like `rustls` and `idna`) are rather expensive in terms of binary size and are routinely showing up in the top 10 of `cargo bloat` on my applications. As well as causing significant overhead in compile times. 

Considering I only intend to use static resources bundled with the program, including an HTTP client and TLS library and all the related baggage seems very unnecessary.

I'd also like to see these dependencies made optional if possible. @pragmatrix

**Comment by pragmatrix** [comment]
Beginning with version 0.80 of skia-safe, `ureq` is now a separate feature that can be enabled optionally. For the simplest usage of using the SVG Dom, only a (default or empty) FontMgr needs to be provided. Details are in #1024.
