### ISSUE TITLE
FontStyleSet::match_style seems to use an unnecessary parameter index

### ISSUE THREAD

**Issue by jianse** [rust-skia/rust-skia#1008]
https://github.com/rust-skia/rust-skia/blob/713ecd28669911228c3fa03a4a2c90fe50bf3813/skia-safe/src/core/font_mgr.rs#L73-L78

The `index` parameter seems not being used by under layer C api. But only in rust api.

**Comment by pragmatrix** [comment]
Thank you, the parameter got removed.
