### ISSUE TITLE
Vulkan on Android armv7

### ISSUE THREAD

**Issue by triniwiz** [rust-skia/rust-skia#1009]
I'm trying to enable vulkan but the build never gets pass "Generating bindings" it only fails with the `armv7-linux-androideabi` target .

Some error I extracted  `Cannot turn unknown calling convention to tokens: 7` mentions `bindgen-0.69.4/ir/function.rs:263:34`. 

Atm I'm trying to use `gl, vulkan & textlayout`

**Comment by pragmatrix** [comment]
@triniwiz I was able to reproduce this with a r26d Android NDK and preventing bindgen from creating bindings for the function PFN_vkVoidFunction did the trick. Please take a look at the current master branch to see if it works for your build environment.

**Comment by triniwiz** [comment]
@pragmatrix thank you that fixed the building.
