### ISSUE TITLE
Alpine: Don't hardcode C++ stdlib version

### ISSUE THREAD

**Issue by Janrupf** [rust-skia/rust-skia#1015]
https://github.com/rust-skia/rust-skia/blob/5053d4dbf463714df7177b648eacf466eb57d5d4/skia-bindings/build_support/platform/alpine.rs#L27-L32

This causes build failures where the C++ stdlib can't be found on newer alpine installations. Instead the version should be detected automatically.

**Comment by pragmatrix** [comment]
Closed via #1067
