### ISSUE TITLE
The code of the skia-bindings-0.75.0 crate seems to be incomplete

### ISSUE THREAD

**Issue by WZY1999428** [rust-skia/rust-skia#1026]
When I use freya gui to install the latest version, it fails to run successfully and prompts the following error
![image](https://github.com/user-attachments/assets/520b965e-7eef-4653-a9f2-fed97eb65078)

**Comment by pragmatrix** [comment]
Thanks, this will be fixed in 0.78 / Milestone 129 (#1022), which will be released as soon as possible.

**Comment by WZY1999428** [comment]
> Thanks, this will be fixed in 0.78 / Milestone 129 (#1022), which will be released as soon as possible.

Thanks, and I look forward to the release of version 0.78!
