### ISSUE TITLE
Building on MacOS with libjpeg-turbo compile errors.

### ISSUE THREAD

**Issue by therealbnut** [rust-skia/rust-skia#103]
Hey,

I had some compile errors related to `libjpeg` (you can see other people getting the same errors here: https://github.com/aseprite/aseprite/issues/1981).

I tried `brew install libjpeg-turbo` but that didn't work, in the end I had to put  `("skia_use_libjpeg_turbo", no()),` into `build.rs` to get it building.

I'm not sure if that's a change you want to include unconditionally, but I thought I should mention it in case someone else has the same issue.

**Comment by Brooooooklyn** [comment]
Have you tried to install `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` ?

**Comment by therealbnut** [comment]
I did, but I might need to re-verify again.

I also had to fix some issues with my python install so I re-installed my Xcode CLI tools. I’ll re-verify tomorrow without the build.rs changes, just in case it’s no longer needed.

**Comment by therealbnut** [comment]
That works thanks :D

For reference this was what happened:
 * Try to build, but had issues where it couldn't find system `python` (I had a brew version instead)
 * Run `macOS_SDK_headers_for_macOS_10.14.pkg`, but that didn't fix it
 * Fixed `python` by reinstalling the system python by clean installing Xcode CLI tools (this removed `TargetConditionals.h`, but I didn't realise)
 * Run into `libjpeg-turbo` issue
 * Fix `libjpeg-turbo` by modifying `build.rs`
 * Have `TargetConditionals.h` issue for the first time
 * Run `macOS_SDK_headers_for_macOS_10.14.pkg` again (which removed the need for the `build.rs` change but I didn't realise)

**Comment by pragmatrix** [comment]
Thanks for the detailed feedback! I will try to reproduce that and update the readme.
