### ISSUE TITLE
Shaders are not working on macOS/OpenGL

### ISSUE THREAD

**Issue by zolbatar** [rust-skia/rust-skia#1036]
Everything is working great for me using the latest skia-safe bindings (0.78.1), with the exception of shaders. Any type of shader effects either crashes out or gives unexpected results:

set_path_effect: White screen and seems to lock up.
blur and drop_shadow_only:

```
(anonymous namespace)::make_drop_shadow_graph(SkPoint, SkSize, SkRGBA4f<(SkAlphaType)3>, sk_sp<SkColorSpace>, bool, sk_sp<SkImageFilter>, std::__1::optional<SkRect> const&) 0x0000000100dbfb74
SkImageFilters::DropShadowOnly(float, float, float, float, SkRGBA4f<(SkAlphaType)3>, sk_sp<SkColorSpace>, sk_sp<SkImageFilter>, SkImageFilters::CropRect const&) 0x0000000100dbff70
C_SkImageFilters_DropShadowOnly 0x000000010107aebc
skia_safe::effects::image_filters::drop_shadow_only image_filters.rs:285
PolisAndSiege::lib::skia::Skia::new skia.rs:57
PolisAndSiege::main main.rs:39
core::ops::function::FnOnce::call_once function.rs:250
std::sys::backtrace::__rust_begin_short_backtrace backtrace.rs:152
std::rt::lang_start::{{closure}} rt.rs:162
[Inlined] core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once function.rs:284
[Inlined] std::panicking::try::do_call panicking.rs:557
[Inlined] std::panicking::try panicking.rs:521
[Inlined] std::panic::catch_unwind panic.rs:350
[Inlined] std::rt::lang_start_internal::{{closure}} rt.rs:141
[Inlined] std::panicking::try::do_call panicking.rs:557
[Inlined] std::panicking::try panicking.rs:521
[Inlined] std::panic::catch_unwind panic.rs:350
std::rt::lang_start_internal rt.rs:141
std::rt::lang_start rt.rs:161
main 0x0000000100bfedbc
start 0x0000000192278274
```

This is the same either using the winit GL method of creating a window or using raylib and writing to a raylib texture.

Any ideas what I am doing wrong? Similar code in C++ on the same machine works fine.

Setting up the dashed paint seems like I'm doing it the only way?

```        let mut paint = Paint::default();
        paint.set_anti_alias(true);
        paint.set_argb(255, 20, 20, 20);
        paint.set_stroke_width(0.25);
        paint.set_style(PaintStyle::Stroke);
        let dash = PathEffect::dash(&[1.0, 0.5], 0.0).unwrap();
        paint.set_path_effect(dash);
```

**Comment by pragmatrix** [comment]
> Any ideas what I am doing wrong?

I am getting a SIGSEGV in
```
    #[test]
    fn test_drop_shadow_only() {
        let rect = Rect {
            left: 1.0,
            top: 2.0,
            right: 3.0,
            bottom: 4.0,
        };
        let crop_rect = CropRect(Some(rect));

        let offset = Point::new(10., 10.);

        let _ = super::drop_shadow_only(offset, (1.0, 1.0), 0x404040, None, None, crop_rect);
    }
```

so there is definitely a problem with the wrappers. From a first glance this looks like an alignment problem with the Color4f parameter. The bindings somehow fail to transfer the arguments correctly to C causing the color space argument pointing to weird memory location which then segfaults when the reference counter gets increased. Looking into it.

**Comment by pragmatrix** [comment]
I think I've found and fixed the drop_shadow segfaults in #1037. And there was also a problem with passing the crop rect to the shaders, which may have caused the unexpected behavior. 

I would appreciate if you could test that branch with your shader code.

**Comment by zolbatar** [comment]
Wonderful! Love to give it a go later, can I reference the branch from my Cargo.toml? I've not done this before...

So glad there was an actual issue, I spent hours debugging this!

**Comment by pragmatrix** [comment]
> Or do I clone the branch and reference it by directory?

Yes, that's my preferred method. I would check out the repository `git@github.com:rust-skia/rust-skia.git`, cd into `rust-skia`, and then use the gh command line tool as shown in the right top "code" button: `gh pr checkout 1037`, and then set the reference in `Cargo.toml` with `path` pointing to `rust-skia/skia-safe`.

**Comment by zolbatar** [comment]
Initial observation is that it no longer crashes creating a drop shadow.

But if I specify a crop rect of anything but 1,2,3,4 it gives me a white screen. With those values I don't see a drop shadow at all, but it doesn't fail.

I tried with None as crop rect and it gave me a white screen.

**Comment by zolbatar** [comment]
After doing more testing, there is a definite issue with shaders - presumably not being compiled correctly?

The dash line effect is the most obvious example. I just get a white screen if I try and use it.

**Comment by pragmatrix** [comment]
I've tried the skia-org/ example on macOS (Apple Silicon) with `--driver open-gl` and it renders dash paths as expected. You can try it yourself with `cargo run --features gl -- --driver open-gl` and the resulting images should be in the opengl/ directory.

To continue, I need a minimal reproducible example for the remaining issues.

**Comment by zolbatar** [comment]
The demo works but it's rendering to a surface and then saving it. The interaction with the GPU when flushing contexts and getting the GPU to run shaders I am sure is getting messed up somehow.

I'm going to try and create a very simple example to try and dig into what is happening. I may need properly reset GPU state somewhere.

**Comment by zolbatar** [comment]
Just an FYI, you can close this off. I rebuilt everything to use SDL2 and render in a simpler way and all shaders work.

Builders for shaders would be VERY useful though!

Thanks for looking into this.
