### ISSUE TITLE
Missing prebuilt skia binary of x86_64-apple-darwin-metal-gl-textlayout combination, aka, BOTH OpenGL and Metal simultaneously.

### ISSUE THREAD

**Issue by crupest** [rust-skia/rust-skia#1052]
Recently we are adding Metal renderer to [Neovide](https://github.com/neovide/neovide/pull/2461). And we are useing skia-safe, which is very amazing work indeed.

The problem is, we already have an OpenGL renderer and just want to add support of Metal and keep BOTH of them. So we need to use a prebuilt skia binary of x86_64-apple-darwin-**metal**-**gl**-**textlayout** combination for both supports of OpenGL and Metal at the same time.

However, according to the release page https://github.com/rust-skia/skia-binaries/releases, there are only
- x86_64-apple-darwin-gl-textlayout (ONLY OpenGL)
- x86_64-apple-darwin-metal-textlayout (ONLY Metal)

In contrary, Windows does have one with both support of D3D and OpenGL,
- x86_64-pc-windows-msvc-d3d-gl-textlayout (BOTH D3D and OpenGL)

Though we can definitely build it by ourselves with powerful auto building function of rust-skia, the problem comes with the same reason. We can but we want a prebuilt one to accelerate development and building , and also to avoid building error caused by the complexity of building skia from scratch.

So, I want to ask,
1. Is this intentional?
2. If not, can I make a pr and add this combination?

Best regards!

**Comment by pragmatrix** [comment]
> Is this intentional?

Yes and no, minimizing the number of binaries is intentional as long there is no auto-upgrade option (yet) to a superset of features when a subset was requested.

> ... can I make a pr and add this combination?

Sure. Add them to `mk-workflows/src/config.rs`

**Comment by crupest** [comment]
Really thanks. I really appreciate it. I'll make a pr later.
