### ISSUE TITLE
`get_points` not working as expected

### ISSUE THREAD

**Issue by velyan** [rust-skia/rust-skia#131]
Hey,

Is there an example showcasing how to use [`get_points`](https://github.com/rust-skia/rust-skia/blob/91e8a352e27da29c44905d5f05f421243778babf/skia-safe/src/core/path.rs#L482)?

```
let count = self.path.count_points();
let mut points = Vec::with_capacity(count);
let c = self.path.get_points(&mut points);
```
I can't get it to update the array I am passing with points.
Probably I am doing something wrong, sorry 🤷‍♀️

**Comment by pragmatrix** [comment]
I think you need to resize the vec not set the capacity, otherwise `&mut points` will pass an empty slice.

**Comment by pragmatrix** [comment]
That will work:

```Rust
let points_count = path.count_points();
let mut points = vec![Point::default(); points_count];
let count_returned = path.get_points(&mut points);
```

**Comment by velyan** [comment]
Thanks @pragmatrix!
