### ISSUE TITLE
API doesn't allow creation of image filter without input

### ISSUE THREAD

**Issue by jazzfool** [rust-skia/rust-skia#218]
Image filters cannot be created without passing in a valid `input` parameter, [example](https://github.com/rust-skia/rust-skia/blob/master/skia-safe/src/effects/image_filters.rs#L55).

Passing in `nullptr` is valid in the original Skia API, it should be reflected the same here.

**Comment by pragmatrix** [comment]
Thank you @jazzfool for reporting these API inconsistencies. A fix will be in the upcoming 0.19 release.
