### ISSUE TITLE
Do I need to install Python on MSYS2 and Windows Shell? Only need to install one, according to my preference.

### ISSUE THREAD

**Issue by 3442853561** [rust-skia/rust-skia#225]
Do I need to install Python on MSYS2 and Windows Shell? Only need to install one, according to my preference.

**Comment by pragmatrix** [comment]
Hi, as long Python2 can be found in an MSYS2 shell by entering `python` or `python2`, the build script will pick the correct executable for the Skia build. So installing the MSYS2 package `python2` with `pacman -S python2` should be sufficient.

**Comment by 3442853561** [comment]
@pragmatrix Thank you for so patiently explaining this to me. However, is there any other way to use this crate if I don't have MSYS installed?

**Comment by pragmatrix** [comment]
Oh, sry, than I misunderstood your question, yes, either shell should work as long Python2 is installed and is the PATH. I've just successfully built it with `cmd.exe` and Windows Python 2.7.17 installed from https://www.python.org/downloads/release/python-2717/.

**Comment by pragmatrix** [comment]
Closing this, please reopen if my answer wasn't resolving the issue.
