### ISSUE TITLE
OpenGL interface using custom `get_proc_address()` function

### ISSUE THREAD

**Issue by katyo** [rust-skia/rust-skia#235]
Skia has an `GrGLMakeAssembledInterface()` function which can help create interface using GL procedure address get function which provided by user.
I have a troubles with initializing skia context on several platforms, so I think that possibility can help me in it.
Are you welcome PRs?

**Comment by pragmatrix** [comment]
> Are you welcome PRs?

Of course!

**Comment by pragmatrix** [comment]
Thank you a lot, #236 was merged tomaster.
