### ISSUE TITLE
TextBlobBuilder alloc_run_pos_h doesn't borrow font

### ISSUE THREAD

**Issue by Kethku** [rust-skia/rust-skia#242]
alloc_run_pos_h consumes the font argument which is inefficient and weird because other similar methods do not. I think this is a bug.

**Comment by Kethku** [comment]
Specifically: https://github.com/rust-skia/rust-skia/blob/b57413004533a84990c3caf51c2db188256da0cf/skia-safe/src/core/text_blob.rs#L175

**Comment by pragmatrix** [comment]
> I think this is a bug.

It surely is. The C++ header files are also expecting a `Font` reference. I'm trying to get this released as soon as possible.

**Comment by pragmatrix** [comment]
Binaries and crates are updated. Version 0.23.0.

**Comment by Kethku** [comment]
Thank you so much!
