### ISSUE TITLE
Proposal: remove features svg and shaper

### ISSUE THREAD

**Issue by pragmatrix** [rust-skia/rust-skia#261]
I'd like to remove the features `svg` and `shaper`, because 

- The SVG generator is small and it can be embedded directly in the no-features / default build.
- SkShaper is hard to use directly and lacks a number of useful features, so I assume that `textlayout` (which requires `shaper`) is almost always used anyway for extended text layout.

Assuming that tree shaking removes all code that is not used, this change should not effect the size of the final executables. I'll try to confirm that with some tests later.

This would also make the binaries generation less confusing and because the only features left would be `vulkan` and `textlayout`, we would be able to provide all 4 possible combinations per platform.

**Comment by messense** [comment]
I am currently only use the `shaper` feature, but I don't mind enabling `textlayout`  as long as the existing `TextBlob` code still works.

**Comment by messense** [comment]
Pre-built binaries aren't usable for me on Linux because they are built on Ubuntu 18.04 while I'm deploying on CentOS 7.

**Comment by pragmatrix** [comment]
@messense Thank you for the feedback!

There will be no changes in the `shaper` specific functionality if `textlayout` is enabled.

And for the Linux prebuilt binaries, I will try to find out if something can be done about these ABI differences. It's time to build rust-skia on other distributions anyway.

**Comment by pragmatrix** [comment]
Just checked on Windows that the binary size of release builds does not increase if SVG / XML features are not used. I'm preparing the PR.

**Comment by pragmatrix** [comment]
Closed via #273 and #274
