### ISSUE TITLE
Is there any way to build rust-skia without libGL dependency?

### ISSUE THREAD

**Issue by messense** [rust-skia/rust-skia#267]
Or could rust-skia link to a static libGL library instead of system's shared dylib?

**Comment by messense** [comment]
Currently I have built a `.so` file with a lot of dylib dependencies:

```
        linux-vdso.so.1 =>  (0x00007ffebbffe000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f46e6f4b000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007f46e6cb4000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f46e6a72000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f46e67b3000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f46e65af000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f46e63a7000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f46e618b000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f46e5f75000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f46e5bb3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f46e7afc000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f46e58b1000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f46e5687000)
	libglapi.so.0 => /lib64/libglapi.so.0 (0x00007f46e5459000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f46e5234000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f46e5022000)
	libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007f46e4e1f000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f46e4c19000)
	libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00007f46e4a17000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f46e46d9000)
	libxcb-glx.so.0 => /lib64/libxcb-glx.so.0 (0x00007f46e44be000)
	libxcb-dri2.so.0 => /lib64/libxcb-dri2.so.0 (0x00007f46e42b9000)
	libxcb-dri3.so.0 => /lib64/libxcb-dri3.so.0 (0x00007f46e40b5000)
	libxcb-present.so.0 => /lib64/libxcb-present.so.0 (0x00007f46e3eb2000)
	libxcb-randr.so.0 => /lib64/libxcb-randr.so.0 (0x00007f46e3ca1000)
	libxcb-xfixes.so.0 => /lib64/libxcb-xfixes.so.0 (0x00007f46e3a99000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007f46e388b000)
	libxcb-shape.so.0 => /lib64/libxcb-shape.so.0 (0x00007f46e3687000)
	libxcb-sync.so.1 => /lib64/libxcb-sync.so.1 (0x00007f46e3480000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f46e3258000)
	libxshmfence.so.1 => /lib64/libxshmfence.so.1 (0x00007f46e3056000)
	libXxf86vm.so.1 => /lib64/libXxf86vm.so.1 (0x00007f46e2e50000)
	libdrm.so.2 => /lib64/libdrm.so.2 (0x00007f46e2c3e000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f46e2a39000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f46e2823000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f46e2613000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00007f46e23e8000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f46e2187000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f46e1f62000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f46e1d5e000)
```

**Comment by messense** [comment]
https://github.com/bytedeco/javacpp-presets/tree/master/skia

The skia build in bytedeco's javacpp-presets only depends on:

```
        linux-vdso.so.1 =>  (0x00007ffe321e8000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fb281841000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb281625000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007fb28137f000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007fb281143000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fb280e3a000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fb280b38000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb280922000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb280560000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb282f78000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007fb280336000)
```

**Comment by messense** [comment]
Or can I just disable `GPU`(OpenGL & Vulkan) feature completely?

**Comment by messense** [comment]
For the record, I am using `rust-skia` to generate PDF files, I don't think GPU feature is really need?

**Comment by pragmatrix** [comment]
If possible, we should definitely support a build without GPU support.

There is this Skia build flag `skia_enable_gpu` which, when set to `false`, will define `SK_SUPPORT_GPU=0` that may result in a build containing CPU rendering code only.

I am suggesting to add a new feature named `gl`, which is set as the new default, and then set `skia_enable_gpu` to `false` as soon neither `gl` nor `vulkan` is set.

Regarding linking to OpenGL statically. What happens if you tell cargo in `skia-bindings/build_support/skia.rs` to link with [`static=GL`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script)?

**Comment by pragmatrix** [comment]
`static=GL` does not work, assuming that there OpenGL is not meant to be linked statically, but removing the dependency altogether does work on my Ubuntu 19 VM. As I can remember, Skia resolves the OpenGL entry points dynamically as soon the OpenGL interface is generated. So this might be an option for you based on the current master.

**Comment by messense** [comment]
I'll give that a try.

**Comment by messense** [comment]
@pragmatrix Confirmed that #268 works for my use case.

**Comment by pragmatrix** [comment]
Ok, your mileage may vary, and seems to depend on dead code elimination of the linker you are using. For example building a debug version of Skia (``SKIA_DEBUG`) does not link, and the linker errors appear as soon skia-safe is compiled.

**Comment by pragmatrix** [comment]
@messense #269 could be interesting for you. Without GPU & OpenGL support the build is reduced from ~900 to about 500 cpp files. I am considering to support this in the Milestone 80 update.

**Comment by messense** [comment]
@pragmatrix Great, thanks!
