### ISSUE TITLE
Not building on Windows 10

### ISSUE THREAD

**Issue by MNTRA** [rust-skia/rust-skia#283]
### Compiling skia-bindings on Windows 10 causes this error.
----
    $ cargo run
       Compiling skia-bindings v0.26.1
       
    error: failed to run custom build command for `skia-bindings v0.26.1`
    
    Caused by:
      process didn't exit successfully: `E:\Development\rust\skia_test\target\debug\build\skia-bindings-01b32c142a9f23b6\build-script-build` (exit code: 101)
    --- stdout
    cargo:rerun-if-env-changed=SKIA_DEBUG
    HOST: i686-pc-windows-msvc
    cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
    cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
    TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.26.1/29ac6844ab1f5f259d6e-i686-pc-windows-msvc
      FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.26.1/skia-binaries-29ac6844ab1f5f259d6e-i686-pc-windows-msvc.tar.gz
    DOWNLOAD AND INSTALL FAILED: [6] Couldn't resolve host name
    STARTING A FULL BUILD
    cargo:rerun-if-env-changed=LLVM_HOME
    DOWNLOADING: https://codeload.github.com/google/skia/tar.gz/97c9a95908
    
    --- stderr
    Checking for "C:\\Program Files\\LLVM\\bin\\clang-cl.exe"
    thread 'main' panicked at 'Failed to download https://codeload.github.com/google/skia/tar.gz/97c9a95908', C:\Rust\cargo\registry\src\github.com-1ecc6299db9ec823\skia-bindings-0.26.1\build_support\skia.rs:1150:37
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

From first glance it looks like the "29ac6844ab1f5f259d6e-i686-pc-windows-msvc" part of the URL doesn't match the URL where the binaries are hosted. 

Am I doing something wrong ?

**Comment by pragmatrix** [comment]
We don't generate prebuilt binaries for 32 bit architectures, and the Windows 10 is you are building on seems to be 32-bit: `HOST: i686-pc-windows-msvc`. So the first error is to be expected.
 
But the full build should be able to download Skia archives from  `https://codeload.github.com/google/skia/tar.gz/97c9a95908`, which succeeds when I enter this URL in a browser, but in the log above, both download attempts indicate that there is a problem with the Internet connection or name resolution.

**Comment by MNTRA** [comment]
I'm not sure why I had the 32 bit toolchain installed...
I installed the 64bit toolchain and it built without any problems

**Comment by pragmatrix** [comment]
Very well, and thank you for the feedback. I am closing this issue.
