### ISSUE TITLE
Create support for embedded ARM devices like the Raspberry Pi

### ISSUE THREAD

**Issue by rprata** [rust-skia/rust-skia#285]
It's interesting to provide a embedded ecosystem for this library.

**Comment by pragmatrix** [comment]
Sure, but without anyone stepping in for trying to get this started on a concrete target device, I suspect that this request is not actionable. 

A first step is probably to take a look what Skia itself supports and what toolchain needs to be installed on the host to get [clang cross-compilation](https://clang.llvm.org/docs/CrossCompilation.html) set up. I can imagine a similar solution like the Android builds, which require a customized clang / LLVM installation, libraries, and executables for each host and target combination.

I'd like to keep this issue open for a while to see if there is more interest in this area.

**Comment by rprata** [comment]
@pragmatrix, 
I think the best target device to start is raspberry pi 2 or 3.

**Comment by pragmatrix** [comment]
Even though we do not run CI tests, building for arm64 Linux distributions should already be possible. Like for Ubuntu, we just supported arm64 in #536. So I am closing this issue. Please open a new one for specific distributions if builds fail or binary releases are needed.
