### ISSUE TITLE
non-compiled

### ISSUE THREAD

**Issue by wellorange** [rust-skia/rust-skia#3]
hello,Can you provide a non-compiled version? I now have the dynamic library of skia and the header file of skia. How can I change it?

**Comment by Brooooooklyn** [comment]
I will provide precompiled static link library after I finished https://github.com/Brooooooklyn/rust-skia/pull/2

**Comment by wellorange** [comment]
I can contribute to this project, but this compilation has failed. I copied libskia.so from others, but I didn't get it.(ubuntu18)

**Comment by Brooooooklyn** [comment]
I don't want commit static link file into `git`. It should generate by `CI`.
In Ubuntu18, you can just follow this two steps to run the example:

1. follow this guide to setup skia tools https://skia.org/user/download
2. `INIT_SKIA=true cargo run --example hello` (this step may require a proxy to access google codes

**Comment by wellorange** [comment]
println!("cargo:rustc-link-lib=static=skiabinding")??????????
What is skiabinding? I compiled skia separately without this file! I am now compiling skia from another server and copying the dynamic library.

**Comment by wellorange** [comment]
我才发现你是中国上海 我北京的

**Comment by Brooooooklyn** [comment]
`skiabinding` is generated by `src/binding.cc`

**Comment by wellorange** [comment]
I have encountered such a problem

orange@orange:~/work/rust/material/rust-skia$ cargo run --example hello
   Compiling rust-skia v0.1.0 (/home/orange/work/rust/material/rust-skia)
error[E0425]: cannot find value `SK_ColorBLACK` in this scope
  --> src/canvas.rs:45:25
   |
45 |       sk_paint.setColor(SK_ColorBLACK);
   |                         ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `SK_ColorWHITE` in this scope
  --> src/canvas.rs:48:44
   |
48 |       SkiaClearCanvas(sk_canvas as *mut _, SK_ColorWHITE);
   |                                            ^^^^^^^^^^^^^ not found in this scope

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `rust-skia`.

To learn more, run the command again with --verbose.
orange@orange:~/work/rust/material/rust-skia$

**Comment by pragmatrix** [comment]
Hello, we are trying to make this library easier to compile, for example #48 is one step in this direction. Also we prepared a readme that should be merged soon, which may be reviewed here #43. In addition to that, @Brooooooklyn is working on providing prebuilt binaries #49.

If there are further compilation problems, please open a new issue and provide the exact platform and the output of the `cargo build -vv`  command.

Closing this in favor of the issues #48, #43, and #49.
