### ISSUE TITLE
How to get image data from a Gpu powered surface using snapshot 

### ISSUE THREAD

**Issue by triniwiz** [rust-skia/rust-skia#306]
Hi so I noticed you call `surface.image_snapshot()` to get an Image followed by `image.encode_to_data` the only problem I have is returning data is usually empty or a blank image

**Comment by pragmatrix** [comment]
Assuming you use the feature `metal`, I've tried setting `Budgeted::NO` in the render target on macOS, but even there, the images came out perfectly fine.

**Comment by pragmatrix** [comment]
Can you provide a repro?

**Comment by triniwiz** [comment]
Still new at rust 🙈  but here goes so I'm creating my surface for android `(GLSurfaceView)` like the following  ... If you're wondering what I'm trying to achieve it's a canvas api similar to the web but for NativeScript this would be for the `toDataURL()` 😁  

```rust
 let interface = gl::Interface::new_native();
    let context = Context::new_gl(interface.unwrap());
    let mut ctx = context.unwrap();
    let mut frame_buffer = gl::FramebufferInfo::from_fboid(buffer_id as u32);
    frame_buffer.format = 0x8058; //GR_GL_RGBA8 (https://github.com/google/skia/blob/master/src/gpu/gl/GrGLDefines.h#L511)
    let target =
        BackendRenderTarget::new_gl((width as i32, height as i32), Some(0), 8, frame_buffer);
    let surface_props = SurfaceProps::new(SurfacePropsFlags::default(), PixelGeometry::Unknown);
    let surface_holder = Surface::from_backend_render_target(
        &mut ctx,
        &target,
        SurfaceOrigin::BottomLeft,
        ColorType::RGBA8888,
        None,
        Some(&surface_props),
    );
    let mut surface = surface_holder.unwrap();
```
All drawing works fine 😸 my only problem is getting the data after doing a snapshot of the surface one thing you should know after all of my canvas related actions I call `surface.flush()` (I noticed there are like 3 `canvas.flush(), canvas.flush(), context.flush()` )


```rust
let mut canvas_native: Box<CanvasNative> = unsafe { Box::from_raw(canvas_ptr as *mut _) };
    let image = canvas_native.surface.image_snapshot();
    Box::into_raw(canvas_native);
    let mut quality = quality;
    if quality > 100 || quality < 0 {
        quality = 92;
    }
    let format = unsafe { CStr::from_ptr(format) }.to_str().unwrap_or("image/png");
    let mut native_format = match format {
        "image/jpg" | "image/jpeg" => EncodedImageFormat::JPEG,
        "image/webp" => EncodedImageFormat::WEBP,
        "image/gif" => EncodedImageFormat::GIF,
        "image/heif" | "image/heic" | "image/heif-sequence" | "image/heic-sequence" => EncodedImageFormat::HEIF,
        _ => EncodedImageFormat::PNG
    };
    let data = image.encode_to_data_with_quality(native_format, quality);
    let mut encoded_prefix = String::new();
    encoded_prefix.push_str("data:");
    encoded_prefix.push_str(format);
    encoded_prefix.push_str(";base64,");
    let data = match data {
        Some(data) => {
            let encoded_data = base64::encode_config(data.as_bytes(), base64::STANDARD);
            let mut encoded_string = String::new();
            encoded_string.push_str(&encoded_prefix);
            encoded_string.push_str(&encoded_data);
            CString::new(encoded_string).unwrap()
        }
        _ => {
            let mut encoded_string = String::new();
            encoded_string.push_str(&encoded_prefix);
            encoded_string.push_str("\"\"");
            CString::new(encoded_string).unwrap()
        }
    };
    data.into_raw()
```

**Comment by pragmatrix** [comment]
Based on parts of your code, I've create a [small example project](https://github.com/pragmatrix/skia-gl) that opens a window with SDL2, draws a red line, and snapshots the framebuffer to a file `snapshot.png`. 

This works on Windows, but I am not sure how it behaves on Android.

**Comment by triniwiz** [comment]
So it works 🤦‍♂  I needed to change around the way I was flushing the canvas and surface then getting the snapshot ... basically on the `GLSurfaceView.Renderer` in the `onDrawFrame` I flush the canvas + surface then I can get data from the snapshot 😄  ... Thanks for the example

**Comment by pragmatrix** [comment]
Ok, thank you for the feedback, I'm glad you figured it out!
