### ISSUE TITLE
Export GrGLFormatToEnum and/or GR_GL_* constants

### ISSUE THREAD

**Issue by nornagon** [rust-skia/rust-skia#311]
Creating a `gpu::gl::FramebufferInfo` that's suitable for gpu rendering requires using the #define form of GrGLFormat, e.g. `GR_GL_RGBA8`. The enum form is exposed via `gpu::gl::Format`, but there's no way currently to convert the enum form to the constant form that's required by `FramebufferInfo`.

Perhaps it would make sense to offer a constructor of `FramebufferInfo` that takes a `Format` and converts it internally?

**Comment by pragmatrix** [comment]
Casting to `Enum` should be possible:

```rust
let _ = FramebufferInfo {
    fboid: 0,
    format: Format::ALPHA8 as Enum,
};
```

compiles, am I missing something?

**Comment by pragmatrix** [comment]
Considering that constructing these types does not seem obviously simple, I would surely accept a PR that adds `::new()` functions to `FramebufferInfo` and `TextureInfo` taking a `Format` type.

**Comment by pragmatrix** [comment]
Now I get it, these are constants with actual different values, thank you for bringing this up! I will prepare a PR that supports the conversions.

**Comment by pragmatrix** [comment]
I've implemented `From` conversions that convert `GrGLFormat` to `GrGLenum` and back. Please take a look at #312 to see if this covers all your usecases.

**Comment by nornagon** [comment]
Yep, #312 seems reasonable to me!

**Comment by nornagon** [comment]
btw, I put together a small example of using rust-skia to render into a native OS window: https://github.com/nornagon/rust-skia-game-test

**Comment by pragmatrix** [comment]
@nornagon Would you mind if I put this example under `skia-safe/examples` and continue maintaining it, the examples in this repository do not cover rendering to a window so far.

**Comment by nornagon** [comment]
@pragmatrix yeah that's no problem, in fact do you mind if I make a PR for it?

**Comment by pragmatrix** [comment]
@nornagon Even better, thank you!
