### ISSUE TITLE
Is there any skia library file compiled by msvc debug?

### ISSUE THREAD

**Issue by libaineu2004** [rust-skia/rust-skia#325]
https://github.com/rust-skia/skia-binaries/releases

I can download the release version of skia library from the website, but I can't find the debug. Is there any?
I hope to provide debug and release libraries for x86 and x64 respectively.
Thank you!

**Comment by pragmatrix** [comment]
No, we publish only Skia release libraries in the prebuilt binary packages.

You'll have to build rust-skia or skia-safe by with the environment variable `SKIA_DEBUG=1` to use Skia in a debug configuration. Also note that `SKIA_DEBUG` is independent of the Rust profile you are building with.

To consider a release of prebuilt binaries for 32 bit targets, or with Skia debug libraries, I'd like to know a bit more about why you need them.

**Comment by libaineu2004** [comment]
> No, we publish only Skia release libraries in the prebuilt binary packages.
> 
> You'll have to build rust-skia or skia-safe by with the environment variable `SKIA_DEBUG=1` to use Skia in a debug configuration. Also note that `SKIA_DEBUG` is independent of the Rust profile you are building with.
> 
> To consider a release of prebuilt binaries for 32 bit targets, or with Skia debug libraries, I'd like to know a bit more about why you need them.

thanks for the reply. I am a windows app developer.
1. I want to ask, does the environment variable you mentioned refer to the path in the Windows 7/10 system variable?
E.g:
path = C: \ Windows \ system32; C: \ Program Files \ CMake \ bin;
2. Some users install Windows 32-bit system, so if there are 32-bit library files, the applicability is stronger.

**Comment by pragmatrix** [comment]
Regarding 1. yes, it's similar to the `PATH` variable, you can use an environment variable editor or prepend it before cargo build in a shell like this `SKIA_DEBUG=1 cargo build -vv`.

Regarding 2. I really doubt that this is an issue a development setup, and for users, the prebuilt binaries are _not_ separately distributed in a final product, they are statically linked into the resulting executable which should be released. End users won't build rust-skia or the Skia library.

**Comment by libaineu2004** [comment]
ok.thank you.
