### ISSUE TITLE
Subpixel Anti Aliasing for Text Rendering

### ISSUE THREAD

**Issue by Vengarioth** [rust-skia/rust-skia#331]
Hello everyone, first thank you all so much for putting in the work for rust-skia.

I played a little with the project and did not manage to get subpixel text rendering to work. I used skiasharp before and they had a [flag for this on SkPaint](https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skpaint.lcdrendertext?view=skiasharp-1.68.1). all i could find in the rust-skia sources is [this commented line](https://github.com/rust-skia/rust-skia/blob/448537d9967b693fe09a0f8c2ad156176cc75bad/skia-safe/src/core.rs#L108).

My questions are:
1) Is this implemented elsewhere / some other way to achieve it?
2) Or, is this incomplete and if so, i'd like to invest the time to bring it in, but would probably need some mentoring here and there.

Thanks again for this project.

**Comment by pragmatrix** [comment]
I'm not sure, but subpixel rendering should be already possible and the reason that there is no flag in `SkPaint` anymore is most likely because SkiaSharp is based on an older version of Skia.

I guess `Font::set_subpixel()` is probably the function you are looking for.

**Comment by Vengarioth** [comment]
Thanks for the quick response.

That makes sense. I'm following along the code in the paragraph example, but haven't found a way to reach the Font via the FontCollection or FontMgr. Can you give me a hint in the right direction?

**Comment by pragmatrix** [comment]
Quickly scanning through the source of the skparagraph module it seems that there is no way to access the Fonts that are in use. The fonts are created with [`set_subpixel(true)`, but the font edging is set to `AntiAlias` and not `AntiAliasSubpixel`](https://github.com/google/skia/blob/chrome/m81/modules/skparagraph/src/OneLineShaper.cpp#L520-L522), which is probably why they are not rendered like you'd expect to.

I suspect that this is a missing feature that should probably be requested upstream to the Skia repository.

One alternative would be use use the `TextBlob` based functions.

**Comment by pragmatrix** [comment]
Something is off, I've patched the skparagraph module to set `SubpixelAntiAlias`, and also set the proper `SurfaceProps` to specify the pixel layout and the result looked like this when rendered with the CPU:

![image](https://user-images.githubusercontent.com/1003751/80910969-90c68800-8d33-11ea-8214-ea01aebfa420.png)

I am now trying the same with `TextBlob`.

**Comment by pragmatrix** [comment]
Rendering `TextBlob` with a a subpixel anti-aliased font renders still anti-aliased only...

**Comment by Vengarioth** [comment]
Thanks for digging into this, is there any way i could assist?

**Comment by pragmatrix** [comment]
Yes, you could try to create an `TextBlob` example with an actual physical surface, perhaps based on the `skia-safe/examples/gl-example` and / or ask in the Skia mailing list how subpixel rendering is meant to be set up with the new SkFont based APIs.

**Comment by Vengarioth** [comment]
If you want, you can assign this issue to me. But to manage expectations, i'll probably only find time to work on this during weekends.

After some more digging i got RTL text working with the shaper feature, but the layout is still wrong, i'm wondering if this requires the shaper iterators to get right.

The code is in [my fork](https://github.com/Vengarioth/rust-skia/blob/master/skia-safe/examples/text-blob/main.rs). I can open a pull request any time if you like.

![image](https://user-images.githubusercontent.com/1100638/80924272-47545800-8d88-11ea-82f3-cb5e4ba0a3ee.png)

**Comment by pragmatrix** [comment]
Soo, running your example shows me that the subpixel anti-aliasing indeed seems to work when a font is rendered to the OpenGL framebuffer.

Assigning it to you,

and thank you for following up on this, and an example that explains how to properly use text shaping would be a great addition, of course.

**Comment by Vengarioth** [comment]
To report in, i made some progress this weekend and i have some questions. Progress has been slow since i have to read up on a lot of topics left and right.

I don't know if this makes sense, but maybe the the [FourByteTag](https://github.com/rust-skia/rust-skia/blob/e24ae39a2f6dd08b1b1d85b9f077fe0538522ad8/skia-safe/src/core/types.rs#L19) should have some easier way to be constructed for [unicode script properties](https://en.wikipedia.org/wiki/Script_(Unicode)#Special_script_property_values) like it's used [here](https://github.com/google/skia/blob/master/samplecode/SampleTextBox.cpp#L152). What do you think?

Also I'm not sure how to pass a [TextBlobBuilderRunHandler](https://github.com/rust-skia/rust-skia/blob/1a3b764b0eaed10ccb3e48a4025326a377538c2d/skia-safe/src/modules/shaper.rs#L504) as a `&mut dyn RunHandler` to [shape_with_iterators](https://github.com/rust-skia/rust-skia/blob/1a3b764b0eaed10ccb3e48a4025326a377538c2d/skia-safe/src/modules/shaper.rs#L378). Help here would be much appreciated. :D

**Comment by pragmatrix** [comment]
> Also I'm not sure how to pass a TextBlobBuilderRunHandler as a &mut dyn RunHandler to shape_with_iterators. Help here would be much appreciated. :D

I've prepared a PR for that: #338. The new shape_native* functions can be used with `TextBlobBuilderRunHandler`, there is also an example in the tests.

**Comment by pragmatrix** [comment]
> I don't know if this makes sense, but maybe the the FourByteTag should have some easier way to be constructed for unicode script properties like it's used here. What do you think?

Like so #339 ?

**Comment by pragmatrix** [comment]
@Vengarioth I've merged both MRs into master, and will close this issue. If you continue on the text shaping example, please open a new issue, because this one is related to subpixel anti-aliasing only, which seems to generally work as soon an actual framebuffer is used as a rendering target.
