### ISSUE TITLE
Problem building skia lib on Mac OS Catalina (10.15.4)

### ISSUE THREAD

**Issue by StewartCanva** [rust-skia/rust-skia#333]
Hey guys,

more so wondering if anyone's come across anything similar and what they've done to rectify the problem. I'm currently trying to build rust-skia with the native skia lib also being built out instead of using the prebuilt binaries for it (we need it using the freetype backend for what we're working with). However it's seemingly unable to build some of what I assume are the lib c headers.

I'm using LLVM version 10, installed from brew.
I've also set the PATH, LDFLAGS and CPPFLAGS to what the brew command suggested. 

I've attach the build output below:
[build.log](https://github.com/rust-skia/rust-skia/files/4580678/build.log)

The relevant lines are 
> InstalledDir:
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/c++/v1"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/Library/Frameworks"
ignoring duplicate directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /Users/stewart/work/test/rust-skia/skia-bindings/skia
 /usr/local/opt/llvm/bin/../include/c++/v1
 /usr/local/Cellar/llvm/10.0.0_3/lib/clang/10.0.0/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks
 /usr/local/opt/llvm@7/include/c++/v1
 /usr/local/opt/llvm@7/lib/clang/7.0.1/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks (framework directory)
End of search list.
/usr/local/Cellar/llvm/10.0.0_3/lib/clang/10.0.0/include/emmintrin.h:2308:19: error: use of undeclared identifier '__builtin_ia32_pavgb128'
/usr/local/Cellar/llvm/10.0.0_3/lib/clang/10.0.0/include/emmintrin.h:2328:19: error: use of undeclared identifier '__builtin_ia32_pavgw128'

Personally I'm unsure why it would attempt to look in the xcode include directory given we're building it with LLVM.

If anyone's seen anything similar, I would like to know if there was a solution.

Thanks

**Comment by pragmatrix** [comment]
I'm a bit suspicious about these two lines:
```
/usr/local/opt/llvm@7/include/c++/v1
/usr/local/opt/llvm@7/lib/clang/7.0.1/include
```
I'm not sure where these LLVM 7 includes are coming from.

Also your build.log reveals:

```
clang version 7.0.1 (tags/RELEASE_701/final)
```

So my guess is that the clang in the `PATH` is the clang from an LLVM 7 installation that is lurking around.

**Comment by StewartCanva** [comment]
@pragmatrix you are an absolute lifesaver! Thank you so much! 🎊🎉🙌

Apparently I had llvm7 still installed along side llvm10. Not even sure how it was getting to those include locations as llvm7 was not in my `PATH`.

For anyone coming here in the future, solution was to uninstall llvm7
`brew uninstall llvm@7`
