### ISSUE TITLE
Packaging binaries that include skia-bindings is proving difficult.

### ISSUE THREAD

**Issue by theotherjimmy** [rust-skia/rust-skia#340]
I'm packaging neovide, https://github.com/Kethku/neovide, that depends on skulpin, and therefore skia-safe and skia-bindings, for NixOS/nixpkgs. Nix, and many other package managers, require that the code fetch phase is separate from the build phases, which do not have a network connection. You can see my progress here: https://gist.github.com/theotherjimmy/d830cc971c9a9c4f0385eb7bd687d814.

This separation has proven quite difficult to handle with skia-bindings, as part of the `bulid.rs` script either pulls binaries from github or tries to sync the skia repos with git, both off which fail. I have been hacking through the `build.rs` script, and have not yet come up with a method for separating these 2 phases. Ideally, I would like to enhance the build scripts here to allow building of rust-skia based binaries without a downstream fork or a patch, as those would likely be difficult to maintain and brittle.

I'm happy to write Rust and submit pull requests to help in this effort, and I would like advice on how to proceed to make it easier to package binaries such as neovide.

**Comment by pragmatrix** [comment]
I think it should be possible to provide another environment variable that points to a fully configured Skia source tree Ninja can build. Of course given that the configuration matches the one the build script computes based on the current crate feature combination and the `SKIA_DEBUG` environment variable. 

The build could compare the `gn` arguments with the one the Rust `build.rs` script would use and issue a warning if they don't match. `gn` writes them into a file at the target root named `args.gn`.

Assuming that you package based on the crate releases, `depot_tools` is also pulled in as a submodule, but only to download the ninja executable itself. I'd suggested to use one single environment variable that we call something like `SKIA_OFFLINE_GN_ROOT` (a better name could probably be found), which also implies that ninja is preinstalled.

**Comment by theotherjimmy** [comment]
Thanks for the advice, and getting back to me so quickly. I think `SKIA_OFFLINE_GN_ROOT` implies that `build.rs` should not do any network-related actions, and should cover the "we already have ninja" case. I think it would be possible to package neovide and other binaries with this env var available.

**Comment by pragmatrix** [comment]
This is getting a bit more complicated that anticipated. 

First, I think we need another environment variable for specifying where the command should invoked from. And then the build script in it's current form always assumes that the GC build root is a subdirectory `skia` in the current target directory of the build. 

PR #343 is a first step in that direction but does not implement the separation of the directories yet.

**Comment by theotherjimmy** [comment]
That's looking good so far. I was wondering, why are we expecting that the user of an offline build will run `gn` but not `ninja`? I would either expect that a user of an offline build would want to run both themselves, or neither. I'm probably missing something though.

**Comment by theotherjimmy** [comment]
I understand why that was confusing. My script also ran ninja, it was just a bit less obvious.

**Comment by pragmatrix** [comment]
This made everything a lot simpler, I've rudimentarily tested that with#343 and it should just work fine if the `SKIA_OFFLINE_SOURCE_DIR` points to the skia source directory. You should be able to test this with the branch. If that works, I'll merge it and release an updated crate.

**Comment by theotherjimmy** [comment]
Thanks! That's great news. I'll test it as soon as I can.

**Comment by theotherjimmy** [comment]
I take it I'm going to have to provide the "third-party" library source as well, probably in the third-party directory.

**Comment by pragmatrix** [comment]
For that, the packaging script needs to call [tools/git-sync-deps](https://github.com/rust-skia/rust-skia/blob/master/skia-bindings/build_support/skia.rs#L453-L462) with python2 in the fetch phase.

**Comment by pragmatrix** [comment]
Offline builds are supported from now on, #343 covers all the details.
