### ISSUE TITLE
Accessing pixels fails

### ISSUE THREAD

**Issue by j4qfrost** [rust-skia/rust-skia#355]
I've tried almost every avenue I could in order to access the pixels for a frame. I keep running into a situation where the returned data is of 0 width and height. I am on Mac if that's relevant. I know that OSX doesn't use pure Vulkan.

**Comment by pragmatrix** [comment]
We don't have an Vulkan / MoltenVK example that renders to a framebuffer in the repository. I could fabricate something out of an archived project to reproduce this, but the example renderer in skia-org/ already uses Vulkan and even though they use only GPU texture as rendering targets and I haven't tested them recently on MoltenVK, it should work as expected.

Surface creation is described here: 

https://github.com/rust-skia/rust-skia/blob/master/skia-org/src/drivers/vulkan.rs#L66-L76

And `Surface::image_snapshot()` is used to retrieve the pixel data: 

https://github.com/rust-skia/rust-skia/blob/6d1e69e02d725a2951cc1af1869a3dd755cdacdd/skia-org/src/artifact.rs#L16-L18

I don't know how framebuffers in swapchains restricted in terms of CPU access, perhaps you need to copy the pixels to another GPU texture before accessing them from the CPU.

**Comment by pragmatrix** [comment]
And there was also this recent bugfix, which fixed a problem with `Image::peek_pixels`: https://github.com/rust-skia/rust-skia/pull/341

**Comment by j4qfrost** [comment]
So, I updated the skia version, and now I get this error ```'Unable to load create_debug_report_callback_ext'``` Does this mean that I need to do this?  ```use_vulkan_debug_layer(false)``` If so, I ran into another crash that I think is MoltenVK related but will have to investigate.

**Comment by j4qfrost** [comment]
https://github.com/rust-skia/rust-skia/pull/361 This allows ```use_vulkan_debug_layer(false)``` to work, which fixes my issue.

**Comment by j4qfrost** [comment]
Correction, my use case doesn't require ```use_vulkan_debug_layer(false)```
