### ISSUE TITLE
Crash when creating context on macOS using skia-safe 0.30

### ISSUE THREAD

**Issue by aclysma** [rust-skia/rust-skia#358]
When I updated to 0.30 I started crashing when creating a new vulkan skia context.

![image](https://user-images.githubusercontent.com/316070/88500424-97a11780-cf7d-11ea-9b9e-23a7c11a5bc7.png)

Running `cargo update -p skia-safe --precise 0.29.3` to go back to 0.29.3 resolves the crash.

Any ideas on this one? I've opened an issue here in my repo for this: https://github.com/aclysma/skulpin/issues/56

**Comment by pragmatrix** [comment]
I can reproduce that by running the skulpin physics example. No I am trying to see if it happens in a full build and if it's actually skia-safe related.

**Comment by pragmatrix** [comment]
#359 should fix the crash.

For the record, here is the fully symbolicated crash created with `SKIA_DEBUG=1`: https://gist.github.com/pragmatrix/fe4a8f6acdab68fadfaed3b3482bc210


What happens, is the the GrVkAMDMemoryAllocator introduced in Skia 84 accesses fVkExtensions in GrVkBackendContext when the physical device version is < 1.1.0, but vkExtensions was always set to `null`.

**Comment by aclysma** [comment]
Thanks, I grabbed the code from your branch and it resolved the crash. I'll leave the issue open since it's not merged yet but feel free to close it since I can track the PR.

**Comment by pragmatrix** [comment]
Good!, I've merged the branch and the binaries are on their way: https://github.com/rust-skia/rust-skia/runs/917801607

**Comment by pragmatrix** [comment]
Version 0.30.1 is available on crates.io.
