### ISSUE TITLE
IRect and overflow-checks = true

### ISSUE THREAD

**Issue by syrel** [rust-skia/rust-skia#363]
Hi 👋 

After compiling with `overflow-checks = true` I noticed that it panics when trying to compute the height or the width of an `IRect` with top/left as a negative number, for example:

```
IRect { left: 452, top: -257, right: 728, bottom: 111 }
```
thread 'unnamed' panicked at `attempt to subtract with overflow`, skia-safe/src/private/safe32.rs:32:9

Looking at the implementation of `width`:
```
pub fn width(&self) -> i32 {
      sk32::can_overflow_sub(self.right, self.left)
}
```
and corresponding `can_overflow_sub`:
```
pub const fn can_overflow_sub(a: i32, b: i32) -> i32 {
     ((a as u32) - (b as u32)) as i32
}
```
I am not sure I understand the reason behind such substruction. What was the caveat with a direct substraction `right - left` or `bottom - top`?

Cheers
Alex

**Comment by pragmatrix** [comment]
Hello Alex. Honestly I had no idea, I was just a busy bee and ported the original Skia functions:

```c++
// To avoid UBSAN complaints about 2's compliment overflows
//
static constexpr int32_t Sk32_can_overflow_add(int32_t a, int32_t b) {
    return (int32_t)((uint32_t)a + (uint32_t)b);
}
static constexpr int32_t Sk32_can_overflow_sub(int32_t a, int32_t b) {
    return (int32_t)((uint32_t)a - (uint32_t)b);
}
```
... fearing that a naive implementation may cause inconsistencies between the Rust and Skia implementation. 

But following the comment, the Skia implementation was probably naive before which caused an LLVM overflow check to fail which they prevented by casting both values to uint32_t before the substraction.

So I guess the Rust implementation should be the naive substraction here, which the comments in IRect also indicate:

```c++
 /** Returns span on the x-axis. This does not check if SkIRect is sorted, or if
        result fits in 32-bit signed integer; result may be negative.

        @return  fRight minus fLeft
    */
    int32_t width() const { return Sk32_can_overflow_sub(fRight, fLeft); }
```
