### ISSUE TITLE
Bitmap should install_pixels from Pixmap

### ISSUE THREAD

**Issue by colorhook** [rust-skia/rust-skia#373]
I can't draw pixmap data to a canvas, Any problem blow?

```
// bytes is &mut [u8]
let image_info = ImageInfo::new_n32_premul((width, height), None);
let row_bytes = (width * 4) as usize;
let pixmap = Pixmap::new(&image_info, bytes, row_bytes);
let mut bitmap = Bitmap::new();
unsafe {
    bitmap.install_pixels(&image_info, pixmap.writable_addr(), row_bytes);
 }
 canvas.draw_bitmap(&bitmap, (x, y), None);
```

PS: https://fiddle.skia.org/c/@Bitmap_installPixels_3

**Comment by pragmatrix** [comment]
There was a problem with the wrapper function `Pixmap::new` actually ignoring its arguments, which should fixed in master (#352). Can try it from there, and sorry for the inconvenience. If master works for you, I'll release a new crate today.

**Comment by pragmatrix** [comment]
I've just published skia-safe (0.31.0) to crates.io, so, if you use the prebuilt binaries, `cargo update` may fix the problem.

**Comment by colorhook** [comment]
It works after cargo  update, Thanks!!! 😄😄

And there may be a spelling error in `is_clip_rect` method

```
pub fn is_clip_empty(&self) -> bool {
    unsafe { sb::C_SkCanvas_isClipEmpty(self.native()) }
}

pub fn is_clip_rect(&self) -> bool {
    unsafe { sb::C_SkCanvas_isClipEmpty(self.native()) }
}
```

**Comment by pragmatrix** [comment]
Thanks for the feedback, and the bugfix for `Canvas::is_clip_rect` is underway #374.
