### ISSUE TITLE
MaskFilter::blur will panic if called with a sigma of 0.0

### ISSUE THREAD

**Issue by samizdatco** [rust-skia/rust-skia#376]
It seems like the underlying `SkMaskFilter_MakeBlur` function only returns a filter if the `sigma` value is non-zero, so the `blur` function should really return an Option. Currently the function panics on `unwrap` if called with a zero.

https://github.com/rust-skia/rust-skia/blob/fdf06cfd6739ee7027be7520b0f4941cfdeb4bd9/skia-safe/src/core/mask_filter.rs#L28-L33

**Comment by pragmatrix** [comment]
Thank you, and nice catch, this one is on me. #378.
