### ISSUE TITLE
Upgrade to latest skia

### ISSUE THREAD

**Issue by Brooooooklyn** [rust-skia/rust-skia#38]
When I was trying to speedup build by introduce perbuilt static files in [skia-raw](https://github.com/rust-skia/skia-raw)(this repo is just for experiment), I found that skia has removed some API we are using in https://github.com/rust-skia/rust-skia/blob/master/skia-bindings/src/bindings.cpp.
We need upgrade our `bindings.cpp` to make it compatible with latest skia.

/cc @pragmatrix

**Comment by pragmatrix** [comment]
Can't you use the version we are using in this repository?

Generally, I would prefer to keep the version that we are using aligned to an officially _released_ stable Chrome branch (currently this one: https://github.com/google/skia/tree/chrome/m72).

**Comment by pragmatrix** [comment]
I'm preparing a PR that updates skia-bindings and skia-safe to m73 (beta), because I was not able to build m72.
