### ISSUE TITLE
Segfault on repeated invocation of finish_recording_as_picture

### ISSUE THREAD

**Issue by samizdatco** [rust-skia/rust-skia#386]
Calling `finish_recording_as_picture` more than once is semantically invalid, but should probably just return `None` if the `PictureRecorder` is no longer recording. 

At the moment it segfaults the second time it is called. 

https://github.com/rust-skia/rust-skia/blob/b83504106a93216482b97f9bd81620e782778203/skia-safe/src/core/picture_recorder.rs#L59-L68

The other way to detect whether an `SkPictureRecorder` is still active in C++ is to check whether [getRecordingCanvas()](https://api.skia.org/classSkPictureRecorder.html#a9dc9ada02bc06dbe931a0a6744db939e) returns a null pointer. So it might make sense to convert `PictureRecorder`’s `recording_canvas` method to returning an Option as well?
https://github.com/rust-skia/rust-skia/blob/b83504106a93216482b97f9bd81620e782778203/skia-safe/src/core/picture_recorder.rs#L53

**Comment by pragmatrix** [comment]
Thank you, 

and you are right, I've taken a look at the C++ source and `fRecord` is accessed in the `finish` functions and cleared afterwards, which most probably caused the segfaults. #387 implements your suggestions.
