### ISSUE TITLE
no implementation for 'u32 & i32'

### ISSUE THREAD

**Issue by Kethku** [rust-skia/rust-skia#392]
I recently updated skia-safe in neovide by running cargo update. This updated a number of packages, but when trying to build I get the following error:  

```
error[E0277]: no implementation for `u32 & i32`
   --> C:\Users\keith\.cargo\registry\src\github.com-1ecc6299db9ec823\skia-safe-0.32.1\src\gpu\vk.rs:129:31
    |
129 |         ((self.deref() >> 12) & 0x3ff) as _
    |                               ^ no implementation for `u32 & i32`
    |
    = help: the trait `std::ops::BitAnd<i32>` is not implemented for `u32`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `skia-safe`.
```

I'm not sure when this happened and am trying to narrow down which version this appears in. Is this a known issue?

**Comment by Kethku** [comment]
I updated rust and the issue went away. Is there documented a minimum version of rust somewhere required to build skia-safe? Regardless I'm closing as my issue is fixed.

**Comment by pragmatrix** [comment]
This could be related to https://github.com/rust-lang/rust/issues/68951, which Rust 1.45.2 compiles just fine.

> Is this a known issue?

No, the code above was added fairly recently.

> Is there documented a minimum version of rust somewhere required to build skia-safe?

Hmm, this could only be maintained by building with a specific Rust version on the CI with the nice effect of having reproducible builds and binaries. I'll think about that.

**Comment by Kethku** [comment]
Definitely not urgent. Just a passing thought. Thank you for your awesome work.
