### ISSUE TITLE
Missing symbol on linux when using `textlayout` feature

### ISSUE THREAD

**Issue by samizdatco** [rust-skia/rust-skia#393]
I've been building a node module based on skia-safe using [neon](https://github.com/neon-bindings/neon) and have gotten it running smoothly on macOS. I'm currently trying to get it to build on linux and have run into an issue where it seems like some parts of the c++ stdlib aren't being properly linked into the library.

What I've encountered is a compilation phase that looks successful:
```console
root@a67d4b18c303:/source/skia-canvas# neon build
neon info running cargo
    Updating crates.io index
   Compiling cc v1.0.59
   Compiling libc v0.2.76
   Compiling autocfg v1.0.1
   Compiling curl v0.4.33
   Compiling bindgen v0.54.0
   Compiling miniz_oxide v0.4.1
   Compiling atty v0.2.14
   Compiling which v3.1.1
   Compiling socket2 v0.3.12
   Compiling xattr v0.2.2
   Compiling filetime v0.2.12
   Compiling flate2 v1.0.17
   Compiling libz-sys v1.1.0
   Compiling openssl-sys v0.9.58
   Compiling neon-sys v0.4.0
   Compiling libloading v0.5.2
   Compiling curl-sys v0.4.36+curl-7.71.1
   Compiling env_logger v0.7.1
   Compiling clap v2.33.3
   Compiling tar v0.4.29
   Compiling clang-sys v0.29.3
   Compiling neon-build v0.4.0
   Compiling neon-runtime v0.4.0
   Compiling neon v0.4.0
   Compiling skia-canvas v0.1.0 (/source/skia-canvas/native)
   Compiling skia-bindings v0.32.1
   Compiling skia-safe v0.32.1
    Finished dev [unoptimized + debuginfo] target(s) in 36.32s
neon info generating native/index.node
```

But when I try to load the module in node I get:
```console
Welcome to Node.js v14.8.0.
Type ".help" for more information.
> require('./native')
Uncaught:
Error: /source/skia-canvas/native/index.node: undefined symbol: _ZNSt19_Sp_make_shared_tag5_S_eqERKSt9type_info
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1302:18)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
```

I've found that if I comment out the portions of my code that deal with the [Paragraph](https://github.com/rust-skia/rust-skia/blob/master/skia-safe/src/modules/paragraph/paragraph.rs) and [ParagraphBuilder](https://github.com/rust-skia/rust-skia/blob/master/skia-safe/src/modules/paragraph/paragraph_builder.rs) classes, the problem goes away. I'm assuming that the missing symbol stems from this use of `std::make_shared`:

https://github.com/google/skia/blob/735a5a7e82b2dbb247a819cddb376b1fc344a41e/modules/skparagraph/src/OneLineShaper.h#L79-L87

It's unclear to me whether the issue is that the [skia-binaries](https://github.com/rust-skia/skia-binaries) ought to include these libstdc++ routines, or if it's neon’s responsibility to link them in when it creates its derivative library?

**Comment by pragmatrix** [comment]
That `*type_info` symbol that is missing is related to RTTI and is created by the C++ compiler. But Skia gets compiled without RTTI support on Linux, and as it seems `std::make_shared` [may exist in multiple versions](https://stackoverflow.com/questions/43093492/why-does-stdmake-shared-perform-two-separate-allocations-with-fno-rtti), depending if the RTTI is enabled or not, so I guess it depends on how the code is compiled that produces the `index.node` object file.

First, can you try if the skia-org example application can be compiled. And second, try to add the flag `-fno-rtti` here: https://github.com/rust-skia/rust-skia/blob/master/skia-bindings/build_support/skia.rs#L719

**Comment by pragmatrix** [comment]
Probably related: https://groups.google.com/forum/#!topic/skia-discuss/qYEnMbP3VpA

**Comment by samizdatco** [comment]
Oddly the problem only seems to appear when I link against the prebuilt `skia-binaries` release. I tried cloning the rust-skia repo alongside my own and then adjusting my dependency line from
```
skia-safe = {version = "0", features = ["textlayout"]}
```
to
```
skia-safe = {path = "../../rust-skia/skia-safe", features = ["textlayout"]}
```

In the first case, I get the missing symbol error. In the second, it works perfectly (but unsurprisingly takes 10 times as long since it needs to compile all of skia). I didn't end up needing to add any compiler flags either.

I've been testing this in an `ubuntu:bionic` docker image, so it's using glibc 2.7 and libstdc++ 6.0.25 in both cases. Is it possible that the vm that `skia-binaries` is using has a libstdc++ that's too old for what SkParagraph is doing?

**Comment by pragmatrix** [comment]
The VM the Linux binaries are built is an Ubuntu 18.04.5 LTS with the following software installed: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md.

I've checked out the skia-canvas repository in an Ubuntu 20 VM and used `neon build`, started node, and entered `require('./native')`, and the module seems to load:

```javascript
$ node
> require('./native')
{ Canvas: [Function: Canvas],
  CanvasRenderingContext2D: [Function: Context2D],
  CanvasGradient: [Function: CanvasGradient],
  CanvasPattern: [Function: CanvasPattern],
  Path2D: [Function: Path2D],
  Image: [Function: Image],
  ImageData: [Function: ImageData],
  FontLibrary: [Function: SharedFontLibrary] }
> 
```

> Is it possible that the vm that skia-binaries is using has a libstdc++ that's too old for what SkParagraph is doing?

Perhaps, but why then does it work on an Ubuntu 20. We can try to build a round of Linux binaries on the Ubuntu 20 preview that Azure Pipelines offers.

**Comment by samizdatco** [comment]
That mirrors my experience. Running `neon build` (which links against `skia-binaries`) seems to work on Ubuntu 20 but fails with the missing symbol error on Ubuntu 18.

**Comment by pragmatrix** [comment]
It happens without `neon build`, too, the skia-org example can not be linked on an Ubuntu 18 docker VM with the released Linux binaries:

To reproduce:

- create and start a docker vm `ubuntu:bionic`. 
- install rust and a lot more stuff that's appears missing...
- checkout rust-skia release branch
- cd rust-skia
- cd skia-org && FORCE_SKIA_BINARIES_DOWNLOAD=1 cargo run --features textlayout -vv

```
  = note: /root/rust-skia/target/debug/deps/libskia_bindings-f5651d6c44d7f545.rlib(libskparagraph.OneLineShaper.o): In function `std::_Sp_counted_ptr_inplace<skia::textlayout::Run, std::allocator<skia::textlayout::Run>, (__gnu_cxx::_Lock_policy)2>::_M_get_deleter(std::type_info const&)':
          OneLineShaper.cpp:(.text._ZNSt23_Sp_counted_ptr_inplaceIN4skia10textlayout3RunESaIS2_ELN9__gnu_cxx12_Lock_policyE2EE14_M_get_deleterERKSt9type_info[_ZNSt23_Sp_counted_ptr_inplaceIN4skia10textlayout3RunESaIS2_ELN9__gnu_cxx12_Lock_policyE2EE14_M_get_deleterERKSt9type_info]+0x11): undefined reference to `std::_Sp_make_shared_tag::_S_eq(std::type_info const&)'
          collect2: error: ld returned 1 exit status
```

**Comment by pragmatrix** [comment]
Ok, narrowing it down, inspired by this bug: https://gcc.gnu.org/bugzilla//show_bug.cgi?id=88782

... and looking at the paths on the CI realizing that we build the binaries with g++ 9, and a standard Ubuntu-18 runs on g++ 7, and even when I update to g++ 8 the linker error shows up. So it's definitely a binary incompatibility between the libstdc++ in use like suspected earlier, but the other way around: we build the binaries with a newer libstdc++ that is incompatible with gcc / g++ version < 9.

**Comment by pragmatrix** [comment]
I've figured out how to reproduce that locally by using `file://` URLs as download locations for binaries and as soon #400 is merged, I'll try to see if it makes sense to build the binaries with gcc version 7 on Linux and - more specifically - if the [forward ABI compatibility](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html) promise holds in this case.

**Comment by pragmatrix** [comment]
I've managed to create binaries with a docker container, an llvm-9 that refers to 6.0.25 libstdc++ which also builds and links in another container that was upgraded to 6.0.28. So this is the only way to keep the binaries compatible for now. Sadly, I don't see how we can build them on the VMs Azure Pipelines provides us with. So I guess it is time to see if we can utuilize GitHub's new container registry to build the Linux binaries.
