### ISSUE TITLE
Using this library with IMGui

### ISSUE THREAD

**Issue by ctrlcctrlv** [rust-skia/rust-skia#394]
Hello!

I want to make you aware of my modular font editor project, MFEQ.

I'm writing the glyph editor component which heavily relies on this crate, Qglif.

Today I implemented mixing IMGui and Skia. My main.rs is based on one of your examples.

https://twitter.com/HW_BEAT_THAT/status/1299103950570831872/photo/1

I think this is a very common use case, and I found it veyr difficult to get working. Would Qglif itself be a suitable example, or would you prefer some other way of me explaining how I got it to work? It wasn't trivial, at least for me since my only prior OpenGL experience was working on kovidgoyal/kitty

Thanks in advance for the crate

**Comment by pragmatrix** [comment]
Interesting.

It could be valuable for others to see links here that point to projects like yours, especially ones that describe examples of integrations with other UI frameworks. We should put them into the README.md as a start under a section named "Projects that use rust-skia".

So what do you have in mind? Are you willing to set up an open source example that shows your integration attempt with imgui that this project should link to, or would you like to add an example directly to this repository?

**Comment by ctrlcctrlv** [comment]
Hi :-)

The font editor is open source and will be as long as I'm working on it. Apache 2.

https://github.com/mfeq/Qglif

This is the version without ImGui. Some problems remain. You may notice it's oddly green - turns out that's a bug. You may notice the glyphs are yellow boxes. I thought that was because I wasn't loading a font, no, it's also happening for a reason I don't fully understand.

Things are in flux as I think about it and read Skia / ImGui internals / OpenGL manuals. I might decide to go with Qt / QtSkia, of course also via Rust. Rust and Skia are the two I for sure want to use. Everything else is kind of up in the air, "if I get it working / like it" :-) 

I'm just logging off for the night but will take another swing in the AM.

**Comment by ctrlcctrlv** [comment]
Oh, and also, I'd love to hear your opinion @pragmatrix if you've got one: how would you draw a toolbox and/or a right-click menu on top of Skia in skia-safe?

**Comment by ctrlcctrlv** [comment]
@pragmatrix I'm finally ready to release an example that works quite well. 

https://github.com/ctrlcctrlv/imgui-skia-example

![](https://raw.githubusercontent.com/ctrlcctrlv/imgui-skia-example/master/screenshot.png)

See also jazzfool/reclutch#11 :-)

**Comment by ctrlcctrlv** [comment]
Just another update, thanks to help from @jazzfool, Qglif now supports having its window resized. Also, I'm finally using Dear ImGui for the purpose I included it: a toolbox! 

![image](https://user-images.githubusercontent.com/838783/92095131-2168af80-ed8a-11ea-8fa2-74553f49036f.png)

Qglif is probably a better example of using rust-skia and Dear ImGui together, but the previous is much shorter.

**Comment by ctrlcctrlv** [comment]
Sorry to keep replying here @pragmatrix , hope I'm not annoying you.

After mfeq/Qglif#1 and mfeq/Qglif#2, I decided due to jazzfool/reclutch#26 that actually Skulpin is what I really need, and the world is ready for Vulkan after all thanks to MoltenVK (and I don't need to write any custom Mac-only code!). So just for your information I'm going to be porting Qglif away from Reclutch and to Skulpin after @aclysma merges aclysma/skulpin#62.

**Comment by pragmatrix** [comment]
> hope I'm not annoying you.

Absolutely not. Keep going. If you decide to go on with Skulpin, you might want to take a look around at [Neovide](https://github.com/Kethku/neovide)'s issues and see how far you can get and what some of the roadblocks might be.

**Comment by aclysma** [comment]
You might find one of my other project interesting.. the demo shows a property editor built on top of imgui and skulpin: https://github.com/aclysma/imgui-inspect

I also think egui is worth watching: https://github.com/emilk/egui

**Comment by ctrlcctrlv** [comment]
I've been using @matthewblanchard's https://github.com/MFEK/imgui-skia-renderer.rlib, and it seems to fit this need, so closing this. :)
