### ISSUE TITLE
Pointing rust-skia to my fork of Skia

### ISSUE THREAD

**Issue by romanzes** [rust-skia/rust-skia#408]
I had to make some small customizations to Skia library, so I'm trying to make my fork of `rust-skia/rust-skia` to use my fork of `rust-skia/skia`. This is what I did:
1. Forked `rust-skia/rust-skia`
2. Forked `rust-skia/skia`
3. Modified my fork of Skia as I needed, committed and pushed the changes

In `rust-skia`:
1. Changed [Skia URL](https://github.com/rust-skia/rust-skia/blob/master/.gitmodules#L3) in gitmodules
2. Changed skia [package metadata](https://github.com/rust-skia/rust-skia/blob/master/skia-bindings/Cargo.toml#L35) to the short hash of my commit in Skia fork
3. Changed the [dependency URL](https://github.com/rust-skia/rust-skia/blob/master/skia-bindings/build_support/skia.rs#L1276)
4. Committed and pushed the changes

Strangely, after pointing my project to my fork of `rust-skia`, it doesn't look like my changes to Skia are there. Instead it seems to still be using the original `rust-skia/skia` version.

Can somebody point me in the right direction?

**Comment by pragmatrix** [comment]
In the context of a repository build, the commit of the `/skia-bindings/skia submodule` is used and the build script always makes sure to run a `git submodule update` before starting a build: https://github.com/rust-skia/rust-skia/blob/79cc187b10b579324fb4b8e7a7019337161cc3cb/skia-bindings/build_support/skia.rs#L1189-L1198

For experimenting with different Skia versions, comment these lines, or commit the submodule before building.

The dependency URLs and the metadata entries are used in crate builds only.

**Comment by romanzes** [comment]
Thanks @pragmatrix! I committed the submodule and it worked.
