### ISSUE TITLE
How to create a RunHandler to pass to Shaper.shape()?

### ISSUE THREAD

**Issue by aarondail** [rust-skia/rust-skia#409]
I am a newb here (w/ both Rust and Skia) so apologies if I am missing something very simple but I am trying to call the `shape()` method on `Shaper` and can't figure out how to construct a `RunHandler`.  I have code like this:

```
use skia_safe::shaper::{RunHandler, Shaper};
use skia_safe::{Font, FontMgr};

fn test() {
    let font_mgr = FontMgr::new();
    let shaper = Shaper::new(Some(font_mgr.clone()));
    let font = Font::default();
    let mut rh = MyRunHandler {};
    shaper.shape(&TEST_TEXT, &font, true, 100_000.0, &rh);
}

struct MyRunHandler {}

impl RunHandler for MyRunHandler {
    fn begin_line(&mut self) {}
    fn run_info(&mut self, info: &RunInfo) {}
    fn commit_run_info(&mut self) {}
    fn run_buffer(&mut self, info: &RunInfo) -> Buffer { }
    fn commit_run_buffer(&mut self, info: &RunInfo) {}
    fn commit_line(&mut self) {}
}
```

The problem I am hitting is `RunInfo` and `Buffer` are part of the private module `skia_safe::shaper::run_handler` and are not exported from `skia_safe::shaper` (like `RunHandler` itself is).

I see there are some examples of calling `Shaper.shape_text_blob` but that doesn't require a `RunHandler`.

Thanks!

**Comment by pragmatrix** [comment]
@aarondail Thank you a lot for the report. This is a strange oversight I've corrected in #410 with an additional external test case that implements a RunHandler to prevent that from happening again.
