### ISSUE TITLE
Missing APIs: SkPaint.SetTextScaleX, SkPaint.SetTextScaleY

### ISSUE THREAD

**Issue by ctrlcctrlv** [rust-skia/rust-skia#411]
I plan to PR from MFEQ.

**Comment by ctrlcctrlv** [comment]
No longer plan to PR, overlooked `scale` parameter on `Font::from_typeface_with_params`, realized `Typeface::from_data` is the one that's expensive to rebuild every frame, not `Font`. So, I just `lazy_static!`'d the `Typeface` and moved the font constructor into the function.

This remains an issue in principle so I'll leave it open.

**Comment by pragmatrix** [comment]
The functions `setTextScaleX` and `setTextScaleY` were removed from `SkPaint` a long time ago.

**Comment by ctrlcctrlv** [comment]
Oh shit, sorry 😮 

I thought Skia never deprecates stuff. That explains why I couldn't even find it in `skia-bindings`. I thought both needed updating. 🤦‍♂️ 

Sorry&hellip;

**Comment by ctrlcctrlv** [comment]
Here's some assorted progress, hopefully it makes me look not quite as stupid to Googlers ;-)

![2020-09-14 08_37_27-Qglif_  _Inter-Black ufo3_glyphs_uni0051 glif](https://user-images.githubusercontent.com/838783/93109041-67662300-f668-11ea-95c4-ff30c6b5d781.png)
![93093458-91621a00-f655-11ea-80c3-382c886238f8](https://user-images.githubusercontent.com/838783/93109044-67feb980-f668-11ea-8c72-5af668e8ea85.png)
![93104090-46023880-f662-11ea-8c0a-788bb15e08d9](https://user-images.githubusercontent.com/838783/93109045-68975000-f668-11ea-8b26-1dacbecab234.png)

**Comment by pragmatrix** [comment]
@ctrlcctrlv Nice Q

> I thought Skia never deprecates stuff.

I am guessing that the Skia team removes a handful of functions every release (~6 weeks) on average, and also changes signatures for as many functions at least. I try to compensate for the latter, but often it's just not possible to reimplement missing functionality with the result that the wrappers won't probably reach version 1.0 before the Skia team considers changing their policy regarding backward compatibility.

So no, the API surface will most probably change significantly over time with all the pros and cons it brings along. Observing  similar projects like SkiaSharp, which base their API on years old versions of Skia, I decided early on that this project should keep up with the pace Google brings to the table hoping that this makes it easier for active downstream projects to keep up with the small increments.
