### ISSUE TITLE
Please fix docs.rs documentation

### ISSUE THREAD

**Issue by ctrlcctrlv** [rust-skia/rust-skia#412]
Even though most things don't have docstrings, just function name search would save a lot of time.

**Comment by pragmatrix** [comment]
[Build log of skia-bindings.](https://docs.rs/crate/skia-bindings/0.33.1/builds/291764)

In a branch I've included a `bindings_docs.rs` that is used within a docs.rs build. This would probably work, but then I realized that this file needs be generated with every release, making it a maintenance burden while also adding a lot of changes to the repository over time. 

I would rather generate the docs with every release and deploy it either to GitHub pages, or to one of my own servers.

**Comment by ctrlcctrlv** [comment]
I see. For now I'm running `cargo doc` locally, but I think for n00bs it would be good. Your own server and/or GH Pages will eventually show up in Google, plenty of Rustaceans go that route.
