### ISSUE TITLE
Perhaps a compile time feature could make the NativeAccess trait accessible? 

### ISSUE THREAD

**Issue by ctrlcctrlv** [rust-skia/rust-skia#419]
https://github.com/rust-skia/rust-skia/blob/f1af1aaad2871592a57ccbd8cf8ee9850a1f1fea/skia-safe/src/prelude.rs#L191

https://github.com/rust-skia/rust-skia/blob/f1af1aaad2871592a57ccbd8cf8ee9850a1f1fea/skia-safe/src/lib.rs#L27-L28

**Comment by pragmatrix** [comment]
This was asked for a number of times and should probably be featured somewhere more prominently. The [/wrapper.rs module](https://github.com/rust-skia/rust-skia/blob/master/skia-safe/src/wrapper.rs) should cover everything that's needed.
