### ISSUE TITLE
Build failed from missing bindings.rs

### ISSUE THREAD

**Issue by Pytal** [rust-skia/rust-skia#422]
I get the following error when building on Windows
```bash
error[E0583]: file not found for module `bindings`
 --> C:\Cargo\registry\src\github.com-1ecc6299db9ec823\skia-bindings-0.34.2\src\lib.rs:5:1
  |
5 | mod bindings;
  | ^^^^^^^^^^^^^
  |
  = help: to create the module `bindings`, create file "C:\Cargo\registry\src\github.com-1ecc6299db9ec823\skia-bindings-0.34.2\src\bindings.rs"
```

Any solutions?

It may be due to the [build failure](https://docs.rs/crate/skia-bindings/0.34.2/builds/299143) of `skia-bindings 0.34.2`

**Comment by pragmatrix** [comment]
@Pytal An online connection is needed to build rust-skia, and the sandbox in which docs.rs builds rust-skia forbids network access.

I can't see what really happened on your machine and why the build does not work. I've just compiled https://github.com/pragmatrix/rust-skia-test on my Windows machine, and the 0.34.2 build went through. 

It would be very helpful if you could post your build log. Thanks!

**Comment by Pytal** [comment]
@pragmatrix After doing some testing with different build environments I've solved my issue by installing CMake in my build env.
