### ISSUE TITLE
Reading Color4f from Pixmap?

### ISSUE THREAD

**Issue by virtualritz** [rust-skia/rust-skia#441]
I'm very interested in `rust-skia` because it seems to be the only vector graphics crate that is capable of [correct blending](https://skia.org/user/sample/color?cl=9919).

I am using [this example](https://fiddle.skia.org/c/@Color_Type_RGBA_F16) as a guide for the Rust code below. 

As you can see I'm using `unsafe` with some pointer arithmetic to read the `f32` values from the `Pixmap`.

I wonder if there is another way that gets me `Color4f`s somehow? 
I.e. there is `Pixmap::get_alpha_f()` which does return alpha as `f32`. But for color there is only `Pixmap::get_color()` which returns a `Color`. That's data that has been clamped & crunched down to 8bit/channel. Looking at the original Skia C++ docs, this seems to be similarly dire there.

Is there some way to get read `f32`/channel color data from a `Pixmap` w/o `unsafe`?
Or could this be added to the Rust version of Skia?

```rust
use exr::prelude::rgba_image::*;
use skia_safe as sk;

fn main() {
    let width = 256;
    let height = 256;

    let image_info = sk::ImageInfo::new(
        sk::ISize::new(width, height),
        sk::ColorType::RGBAF32,
        sk::AlphaType::Premul,
        sk::ColorSpace::new_srgb_linear().with_linear_gamma(),
    );

    let mut bitmap = sk::Bitmap::new();
    bitmap.alloc_pixels_flags(&image_info);
    let mut offscreen = sk::Canvas::from_bitmap(&bitmap, None);
    offscreen.clear(sk::colors::GREEN);

    let pixmap = bitmap.pixmap();

    let sample = |position: Vec2<usize>| unsafe {
        let index =
            (pixmap.addr().add(position.y() * pixmap.row_bytes()) as *const f32).add(position.x() << 2);
        Pixel::rgba(*index.add(0), *index.add(1), *index.add(2), *index.add(3))
    };

    let image_info = ImageInfo::rgba((width as _, height as _), SampleType::F32);

    image_info
        .write_pixels_to_file("test.exr", write_options::high(), &sample)
        .unwrap();
}
```

**Comment by virtualritz** [comment]
On a sidenote, I modified [the `icon` example to use `Color4f`](https://github.com/virtualritz/skia-test).

Curiously, while the cog renders as expected, the triangles render almost black.

I haven't investigated this but for now it smells like an upstream bug with rendering of `Color4f` gradients under certain circumstances.

**Comment by pragmatrix** [comment]
Hi, `Pixmap::read_pixels` may be what you are looking for, but I think it should be unsafe in its current form, too. Its safety guarantees could be improved by allowing only a certain set of (raw) pixel types.

**Comment by virtualritz** [comment]
I saw `read_pixels()` but it makes a copy of the buffer. I'd very much like to avoid this.
