### ISSUE TITLE
Paint::set_color4f should accept Option<&ColorSpace> instead of &ColorSpace

### ISSUE THREAD

**Issue by JackRedstonia** [rust-skia/rust-skia#456]
Currently, `Paint::set_color4f` has a signature of
```rust
pub fn set_color4f(
    &mut self,
    color: impl AsRef<Color4f>,
    color_space: &ColorSpace,
) -> &mut Self
```
This works, however the `color_space` argument should be of type `Option<&ColorSpace>` because...
- The method on Skia itself has the signature of `void setColor4f (const SkColor4f &color, SkColorSpace *colorSpace=nullptr)`. Notice how the `colorSpace` argument defaults to `nullptr`.
- It's more consistent with `Paint::new`, which also takes an `Option<&ColorSpace>`.

**Comment by pragmatrix** [comment]
Yes, you are right, In #457 I've changed both signatures so that the functions allow passing `None`, `&color_space`, and `Some(&color_space)`.
