### ISSUE TITLE
Builds fail on M1(ARM) Macs

### ISSUE THREAD

**Issue by EthanYidong** [rust-skia/rust-skia#466]
When building `skia-safe` on my arm Mac, I get the error
```
error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch
ninja: build stopped: subcommand failed.
```
even though the clang invocation contains `-target arm64-apple-macos11` and `--target=aarch64-apple-darwin`

A similar error is mentioned [here](https://zulip-archive.rust-lang.org/242906tcompilerarm/44930macOSInitialCIconfiguration.html).

[full output](https://github.com/rust-skia/rust-skia/files/5936181/cargo.txt)

**Comment by EthanYidong** [comment]
`clang --version`:
```
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: arm64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by splatte** [comment]
i think i am having the same issue:

```
% git clone https://github.com/rust-skia/rust-skia
% cd rust-skia ; cargo b
[...]
  clang++ -MD -MF obj/src/codec/jpeg_decode.SkJpegCodec.o.d -DNDEBUG -DSK_SUPPORT_GPU=0 -DSK_ASSUME_GL=1 -DSK_ENABLE_API_AVAILABLE -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -DSK_CODEC_DECODES_JPEG -I../../../../../../skia-bindings/skia -Wno-attributes -fstrict-aliasing -fPIC -fvisibility=hidden -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -target arm64-apple-macos11 -O3 -Wno-sign-conversion -Wno-unused-parameter --target=aarch64-apple-darwin -O0 -isystem /private/tmp/ack/rust-skia/skia-bindings/skia/third_party/libjpeg-turbo -isystem /private/tmp/ack/rust-skia/skia-bindings/skia/third_party/externals/libjpeg-turbo -std=c++17 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -c ../../../../../../skia-bindings/skia/src/codec/SkJpegCodec.cpp -o obj/src/codec/jpeg_decode.SkJpegCodec.o
  error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch
  ninja: build stopped: subcommand failed.
[...]
```

I noticed that clang++ gets passed `-target arm64-apple-macos11` and `--target=aarch64-apple-darwin` which seems to be the underlying issue.

Digging deeper I traced this arg to this part in `skia-bindings/build_support/skia.rs`:

```
@@ -281,7 +281,7 @@ impl FinalBuildConfiguration {
             let target_str: &str = &format!("--target={}", target.to_string());
             let sysroot_arg;
             let opt_level_arg;
-            let mut cflags: Vec<&str> = vec![&target_str];
+            let mut cflags: Vec<&str> = vec![];
```

With this change it builds for me:

```
% cargo clean
% cargo b
[...]
warning: 4 warnings generated.
   Compiling skia-safe v0.38.3 (/private/tmp/ack/rust-skia/skia-safe)
   Compiling skia-org v1.0.0 (/private/tmp/ack/rust-skia/skia-org)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 27s
```

Now I am sure this approach breaks something somewhere else ;), but I am new to rust and this build process goes way over my head. I am happy to try out any PR that someone might come up with based on this finding.

**Comment by Brooooooklyn** [comment]
In [canvas](https://github.com/Brooooooklyn/canvas) , I handle this issue by rewrite clang target: https://github.com/Brooooooklyn/canvas/blob/main/build.rs#L71

**Comment by pragmatrix** [comment]
> I noticed that clang++ gets passed -target arm64-apple-macos11 and --target=aarch64-apple-darwin which seems to be the underlying issue.

@splatte Thank you, this is the correct way to solve this, Skia already sets a `-target` for macOS builds which conflicts with the `--target` skia-bindings sets by default. Without that everything builds and links fine on Big Sur (cross-compiling from Intel to M1 seems to work, too). Though we won't be able to release binaries until Azure supports Big Sur images, #506 should cover the full build.

**Comment by splatte** [comment]
thanks for making this PR, @pragmatrix! I have just tried https://github.com/rust-skia/rust-skia/pull/506 and it builds just fine on M1/macOS big sur 11.2.3/clang 12.0.0.
