### ISSUE TITLE
skia_safe::Color4f should implement Copy

### ISSUE THREAD

**Issue by liquidev** [rust-skia/rust-skia#469]
I personally don't see why it wouldn't implement Copy, it almost seems like an oversight. It's a small type (just 16 bytes), and merely a color, so implicit copies actually make sense. Sometimes you need to reuse a single Color4f in a few places, and having to `.clone()` it explicitly each time can get repetitive quickly. Especially because the regular Color implements Copy.

**Comment by pragmatrix** [comment]
Right, that's an oversight. But I think we should keep the "pass by reference" convention the C++ headers suggest.
