### ISSUE TITLE
Metal-layer as render target (how?)

### ISSUE THREAD

**Issue by fzzr-** [rust-skia/rust-skia#471]
Actually will be great if metal-window example will be there as same as existing gl-window.

I have troubles with... I really don't know what I've missed. Please check out this [Simple demo project][]. There is correct context & render target initialization, but nothing rendered, window is empty. There is should be logo same as in gl-window example.

[Simple demo project][]

_This issue is just a question "What I'm doing wrong?". Need help._ 🤗

[Simple demo project]: https://github.com/fzzr-/rust-skia-metal-window

**Comment by pragmatrix** [comment]
@fzzr- That part you implemented may render on the surface, but the presentation steps seem to be missing. Though I have never done this, it looks similar to Vulkan / D3D swap chains, so I think you need to present the drawable handle that is returned alongside the Surface for each frame that is rendered.

But as I can see, the drawable is always `null` and - skimming through the related Skia sources - meant to be returned asynchronously, meaning that the `Surface::from_ca_metal_layer()` wrapper is probably broken. There is one alternative though, creating a render target directly as shown in the Skia example sources: https://github.com/rust-skia/skia/blob/80bcc2a468bed5cdccdb9de4398805e139848559/tools/sk_app/MetalWindowContext.mm#L88-L104

Also interesting: https://github.com/fzzr-/rust-skia-metal-window/blob/master/src/main.rs

**Comment by fzzr-** [comment]
@pragmatrix ,

Thank you!
I tried and as result now I see 3-4 successfully rendered frames. But next frame - segfault.

I think that is probably because the maximum limit of `drawable`s has been reached, so we should store each `drawable` with `surface` and then circularly get each on for each next frame... Something like triple-buffering but `N`-buffering where `N` is `maximum_drawable_count` for render-target. Probably. I'm totally not sure.

> Also interesting: https://github.com/fzzr-/rust-skia-metal-window/blob/master/src/main.rs

This is my repo with these experiments. :) ([Simple demo project](https://github.com/fzzr-/rust-skia-metal-window))

__I just updated main.rs there.__ Would be great if you check this out and suggest some ideas or PR, please.

**Comment by pragmatrix** [comment]
From the stacktrace of the crash it seems that there is something wrong with a reference count. 

Based on that hunch, increasing the reference count of the drawable with

```
  unsafe { CFRetain(drawable.as_ptr() as *mut _) };
```

before passing it to `TextureInfo::new` fixed the problem, and taking a look at the implementation of Skia's `sk_cf_obj` confirmed that suspicion (sidenote: `CFRetain` is from the crate `core-foundation`). So Skia _does_ need a `CFRetain` before metal objects are used. 

This should get less confusing when reference counted pointers will be added in M89 #460.

> Also interesting ...

I've pasted the wrong link, I meant the example in metal-rs: https://github.com/gfx-rs/metal-rs/blob/master/examples/circle/main.rs

**Comment by pragmatrix** [comment]
Posted the PR: https://github.com/fzzr-/rust-skia-metal-window/pull/1, an update to rust-skia 0.38 fixes the segfault.

**Comment by fzzr-** [comment]
Thanks! For me segfault is already fixed in 0.38.3 crate version.
