### ISSUE TITLE
Weird Windows-only bug cleaning up window

### ISSUE THREAD

**Issue by kognise** [rust-skia/rust-skia#476]
I'm working on an application with a Skia + Glutin stack. I have a weird bug where when closing the window, Skia will hang - the program doesn't exit and cpu usage goes to around 30%.

Here's the thing. This only happens if:
- It's being run on Windows
- The window handle, the graphics context, AND the Skia surface are moved into the closure
- They AREN'T accessed in the order of surface, then context, then handle

**[Here's the smallest reproducible example I could make.](https://github.com/kognise/glutin-weirdness-mcve)**

After some debugging, it looks like it's hanging on `SkSurface#drop`, and specifically might be hanging somewhere in the C++ function [`~GrDirectContext`](https://github.com/rust-skia/skia/blob/80bcc2a468bed5cdccdb9de4398805e139848559/src/gpu/GrDirectContext.cpp#L57).

I'm not very experienced with this, but here's the rough call stack at the hang:

![20210224-021754-procexp64-1.png](https://doggo.ninja/h8xTe6.png)

If you want to experiment, reverse the order of lines 87-89, or comment any of them out, and it'll magically start working.

**Comment by ajkachnic** [comment]
Hmm this seems like a weird windows-only bug cleaning up window?

**Comment by pragmatrix** [comment]
What I can say so far is that it happens in the [gl-window example](https://github.com/rust-skia/rust-skia/tree/master/skia-safe/examples/gl-window), too, and that deadlock appeared first in version 0.33. If the surface creation is moved inside the event loop, your example works, but not when I do the same in the gl-window example.

**Comment by JackRedstonia** [comment]
Encountering this as well in my game engine using winit (https://github.com/rust-windowing/winit/issues/1958). I absolutely did not spend 4 hours messing around with the winit closure trying to find out why it was hanging up on me...

I'll try to reorder the accessing and see if it fixes anything.

**Comment by JackRedstonia** [comment]
funny how this fixes it right up

i'm crying right now and i will not bother to type properly

```rust
event_loop.run(move |event, _, flow| {
        let surface = &mut surface;
        let gr_ctx = &mut gr_ctx;
        let win_ctx = &win_ctx;

        // the rest of your code here
})
```

**Comment by ctrlcctrlv** [comment]
So, something is getting freed when it shouldn't and holding a reference to it stops that?

**Comment by JackRedstonia** [comment]
My guess is that this is more related to drop order. It makes sense to drop the Skia surface first, then the graphics context, then whatever is related to GL stuff, in this case Glutin's WindowedContext.

If my guess is correct that would be rather terrifying.

**Comment by ctrlcctrlv** [comment]
Oh, you're probably right. I don't think it's legal to free a SkSurface after freeing its GrDirectContext. That's a dreaded double free, as freeing GrDirectContext implies freeing SkSurface.

**Comment by JackRedstonia** [comment]
Huh, I wonder how this doesn't explode in one's face when ran on Linux then. I'll valgrind this on Linux to see if it also double-frees there.

Anyhow, how should we mitigate this for skia-safe users as a whole to prevent them from dropping the GrDirectContext first?

**Comment by pragmatrix** [comment]
This is a drop order problem. Dropping of captured variables in move `FnMut` closures seem to get dropped in the order they are [moved into the closure](https://aochagavia.github.io/blog/exploring-rusts-unspecified-drop-order/) and not like in reverse construction order, like we would expect it. Therefore, I think that all the workarounds found so far changed the drop order in the `Fn` closure passed to winit's event loop.

The deadlock happens in `glGetError()` iff the `glutin::ContextWrapper` is dropped before the `DirectContext`, which effectively pulls out the OpenGL (thread local) context from under its feet and leaves `DirectContext`'s destructor with no or an invalid OpenGL context.

This is reproducible in the gl-window example without even going into the event loop:

```rust
    drop(surface);
    drop(windowed_context);
    drop(gr_context);
```

hangs,

```rust
    drop(surface);
    drop(gr_context);
    drop(windowed_context);
```

works.

One additional workaround I found is to parameterize the context with custom `ContextOptions` and set `options.skip_gl_error_checks = context_options::Enable::Yes`, which prevents the invocation of `glGetError()`, but I think the best way to handle this here, and to make the drop order reproducible, is by creating an struct with a either manually controlled drop order or the order we intend.

For example, when we use the following struct and move it inside the event loop's closure, the drop order guarantees that `WIndowedContext` is dropped last:

```rust
struct Env {
    surface: Surface,
    gr_context: DirectContext,
    windowed_context: WindowedContext,
}
```

**Comment by pragmatrix** [comment]
Closing as I don't have any idea how the drop order can modelled into something safe that prevents the deadlock as long the OpenGL context is tied to the current thread. For sure abstractions are possible, but they come with a cost and are out of scope for rust-skia.
