### ISSUE TITLE
Create Bitmap from &[u8]

### ISSUE THREAD

**Issue by liquidev** [rust-skia/rust-skia#481]
I've been looking for a way to create a Bitmap from a slice of bytes, but I haven't found a way to do so. I've found that `install_pixels` exists, but it's an unsafe method, and for good reason: according to the official Skia documentation, one must ensure that the pixel pointer that's passed to `installPixels` must remain valid for the entire lifetime of the Bitmap.

I need all of these gymnastics to load a rendered SVG image from the `resvg` library. It would be convenient if Skia had SVG loading capability built in, but as far as I could tell, it is not capable of doing so.

**Comment by pragmatrix** [comment]
Hello @liquidev. What do you plan to do with the Bitmap? If you want to render it to a Canvas, you are probably better off creating an Image instead. here the `Image::from_raster_data()` should get you started.

There is SVG rendering support in a submodule named modules/svg (kind of hidden behind of a complete SVG DOM implementation, see SkSVGDOM.h) that rust-skia does not wrap yet. However, @Vurich seems to [have started to work on that](https://github.com/Vurich/rust-skia/commit/f4922313447c9aeac761acff6586d725324ea595).

**Comment by pragmatrix** [comment]
I am closing this issue. If you don't get around with resvg, we might consider to open another issue and try to integrate the Skia module.

**Comment by Vurich** [comment]
Yeah I've written a wrapper for the SVG support but it's on my fork which uses a few unstable features of Skia so I can't merge it right now. I actually mean to revisit it since I think there's been a new Skia release which might include the features we need in our product so maybe we'll be able to merge in my work eventually.
