### ISSUE TITLE
Problem with rendering on 0.38

### ISSUE THREAD

**Issue by aclysma** [rust-skia/rust-skia#482]
Hey, I have a skulpin example that stops working when updating to 0.38, it's the physics demo.

**Before (0.37)**
![image](https://user-images.githubusercontent.com/316070/110582163-a14c4980-8120-11eb-9aa6-ffa9d701063c.png)

**After (0.38)**
![image](https://user-images.githubusercontent.com/316070/110582222-ba54fa80-8120-11eb-91d4-01c261e8032c.png)

Was wondering if you've heard of any issues that may have been introduced in 0.38? (more likely, in upstream Skia code between 0.37/0.38)

**Comment by pragmatrix** [comment]
The release of skia-safe 0.38.1 is out and the physics example works with the the following changes against the Skulpin master:

```
diff --git a/skulpin-renderer/Cargo.toml b/skulpin-renderer/Cargo.toml
index dea59bc..41d2095 100644
--- a/skulpin-renderer/Cargo.toml
+++ b/skulpin-renderer/Cargo.toml
@@ -27,7 +27,7 @@ rafx = { version = "=0.0.9", features = ["rafx-vulkan", "framework"] }
 bincode = "1.3.1"
 lazy_static = "1"

-skia-safe = { version = "0.37", features = ["vulkan"] }
-skia-bindings = { version = "0.37" }
+skia-safe = { version = "0.38", features = ["vulkan"] }
+skia-bindings = { version = "0.38" }

 log="0.4"
```
