### ISSUE TITLE
Typeface OpenStream 

### ISSUE THREAD

**Issue by Kethku** [rust-skia/rust-skia#485]
I'm looking at implementing pure rust text shaping via RustyBuzz, but RustyBuzz needs to be able to parse a font in order to shape it. Skia appears to have a way to get the font data from a given typeface via https://api.skia.org/classSkTypeface.html#a48befdd7cb646d78baccad4937c832da but it seems like that hasn't been implemented, and a cursory look into the bindings seems like its not their either.

Is there some way to get at the actual font path or font data that I've missed? If not are there any pointers for interacting with skia's streams so that I could go implement the missing functions?

I know there are bindings for Harfbuzz in skia-safe with the text shaping feature, but I was looking into options that didn't require copying a `icudtl.dat` file to the output directory. Any tips?

**Comment by pragmatrix** [comment]
> Is there some way to get at the actual font path or font data that I've missed? 

Not that I know of, but wrapping the openStream function and returning the contents as a binary blob (Data or vec) shouldn't be a problem.

> ... copying a icudtl.dat file ...

I think I figured out a way to avoid the `icudtl.dat` file on Windows by pushing a pointer to the [included binary](https://github.com/rust-skia/rust-skia/blob/master/skia-bindings/src/icu.rs#L13) from the Rust side to Skia, which in turn initializes ICU with it. I will open a PR soon and see how it behaves. This should also remove the need for calling `icu::init()` in skia-safe on Windows.

**Comment by Kethku** [comment]
Oh wow thanks for the fast response. That PR looks perfect and should unblock integration with rustybuzz.

As far as the ICU file, I went and did what integration I could with the Skia shaper (which I guess wraps Harfbuzz itself?) and ran into the problems I did last time when I tried to use it.
- Ligatures don't seem to work by default
- Font fallback will select the correct font, but won't swap between fonts (I believe this is because I'm using the TextBlob
- Text blobs often change spacing (which makes sense) but won't match the spacing of the original font

I'm not sure what the ligature problem is, but the other two may be fixable by creating a custom run handler. It seems like the TextBlobBuilderRunHandler doesn't pay attention to font changes in text runs and only returns a single TextBlob using the first matching font. Is it possible to create a CustomRunHandler struct which implements the RunHandler trait in Rust? I got confused by the AsRunHandler trait which seems to need a native skia run handler. I found it generally confusing...

In any case, the PR you created looks like it should solve my needs and enable me to use a Rust native shaper which may just be good enough!

**Comment by pragmatrix** [comment]
> Is it possible to create a CustomRunHandler struct which implements the RunHandler trait in Rust?

[like that?](https://github.com/rust-skia/rust-skia/blob/master/skia-safe/tests/shaper.rs#L12).

I assume that Neovide needs strict control over font shaping, but have you tried to use the paragraph module?

**Comment by Kethku** [comment]
I have not looked into the paragraph module as I figured it wouldn't be flexible enough. Does it support monospace fonts? Looks interesting
