### ISSUE TITLE
Does it possible to use for ios/android mobile app?

### ISSUE THREAD

**Issue by vomchik** [rust-skia/rust-skia#488]
Does it possible to use for ios/android mobile app? 
Actually, I'm interested more in skia-binaries.

If yes, could someone write more details, how i can do that?

I want to use Skia as a SVG viewer.

Thanks!

**Comment by ctrlcctrlv** [comment]
The process is a bit complicated, but [Rust is deployable to Android](https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-21-rust-on-android.html). You need to use the NDK.

**Comment by vomchik** [comment]
@ctrlcctrlv i see, thanks 👍
