### ISSUE TITLE
Why is Canvas::get_total_matrix deprecated, and how should I replace it?

### ISSUE THREAD

**Issue by ctrlcctrlv** [rust-skia/rust-skia#492]

**Comment by pragmatrix** [comment]
According to the documentation in `SkCanvas.h` you are supposed to use `local_to_device()` or `local_to_device_as_3x3()` instead. I will update the deprecation warning accordingly.

**Comment by pragmatrix** [comment]
Closed in b34e9791c4ae4225bfc68a56c91da5d3fee18054, furthermore I've converted the C++ documentation of `SkCanvas.h` [to Rust](https://github.com/pragmatrix/rust-skia/blob/m90-document-canvas/skia-safe/src/core/canvas.rs) and will open a PR soon.
