### ISSUE TITLE
Point implements Mul<f32> but doesn't implement Div<f32>

### ISSUE THREAD

**Issue by liquidev** [rust-skia/rust-skia#493]
This makes certain operations unnecessarily convoluted and/or hard to read. See:
```rs
point.into() * (1.0 / self.zoom()) - Point::from(window_size) * 0.5
```
vs
```rs
point.into() / self.zoom() - Point::from(window_size) / 2.0
```

**Comment by pragmatrix** [comment]
Yes, although it's not defined in `SkPoint.h`, I guess implementing `Div` and `DivAssign` can't hurt.

**Comment by pragmatrix** [comment]
#495 implements Div and DivAssign for Point. Closing.
