### ISSUE TITLE
Surface::draw accepts Size instead of a Point, and doesn't accept SamplingOptions

### ISSUE THREAD

**Issue by liquidev** [rust-skia/rust-skia#494]
Looking at the [official Skia reference](https://api.skia.org/classSkSurface.html#a6df6eac244797f29fedd501ce66e4b8c), the x/y parameters are actually coordinates of the point at which the surface should be drawn. I also couldn't find how to pass SamplingOptions to the method, as I want to change the default sampling parameters to something else.

**Comment by pragmatrix** [comment]
You are correct, `Surface::draw` should accept a `Point` or `Vector`, but the signature does support the SamplingOptions argument:

```
    pub fn draw(
        &mut self,
        canvas: &mut Canvas,
        size: impl Into<Point>,
        sampling: impl Into<SamplingOptions>,
        paint: Option<&Paint>,
    )
```

**Comment by liquidev** [comment]
Ah, then maybe I'm running an outdated version of skia_safe. I'll go ahead and update.
