### ISSUE TITLE
Fails to build on Kiss-linux

### ISSUE THREAD

**Issue by Thermatix** [rust-skia/rust-skia#499]
So I'm trying to build Neovide and it fails at `skia-bindings` with (and little else):
```bash
(signal: 11, SIGSEGV: invalid memory references)
```
When I tried building a different branch (opengl) of Neovide, It still fails  at skia-binding but this time it fails when trying to probe for python2 it looks for `["python", "python2"]` which is strange
as I have python 3 installed and doing `python` in the terminal works fine.

Now I know this is a problem when building Neovide but the failure isn't with Neovide but this library, which is why I'm posing this issue here.

I'm not sure what else you need but:

- I have the latest rust stable installed via Rustup
- I have python 3.9.2 installed and it's accessible from the command line (thus it's in the path)
- Kiss standard is built with MUSL
- I'm currently running via a VM (using the VM to bootstrap Linux with an intention to transfer to a laptop)
- I build like this: `cargo build --release --target x86_64-unknown-linux-musl`
- build flags:
    ```bash
    RUSTFLAGS="-C target-feature=-crt-static"
    CARGO_TARGET_X86_64_UNKOWN_LINUX_MUSL_RUST_GLAGS="-C target-feature=-crt-static"
    ```

**Comment by pragmatrix** [comment]
Hmm, it might be a dependency of the `skia-bindings/build.rs` that causes the `invalid memory references` crash. A similar one was mentioned in #454, but so far, I was never able to reproduce this, and as long we don't have a stack trace, I don't see how we are able to continue here. You could help by finding out exactly when and where it happens or by providing a Dockerfile I can base a more detailed analysis on.

The issue with Python is that Google's Skia build needs Python version 2 installed. Python3 won't work. I've tried to port the related scripts to Python3 just to realize that one of the dependencies also needs Python 2. A bit frustrated I was giving up. Is there any chance you could install a Python version 2 inside your build environment for the build script to pick up?

**Comment by Thermatix** [comment]
I can do the python2 thing, for the backtrace, would it be enough to run the build with `RUST_BACKTRACE=1` ?

**Comment by pragmatrix** [comment]
@Thermatix I think the `gn` command may be missing, [this Dockerfile](https://github.com/rust-skia/rust-skia/blob/master/docker/voidlinux-musl/Dockerfile) shows how `gn` can be built and installed on voidlinux. May be that helps.

**Comment by Thermatix** [comment]
Hi @pragmatrix, thanks for this I haven't actually touched my laptop (with KISS on it) in a while (which is why I haven't responded to this issue) but I'm going to be doing stuff on it this weekend so I'll give it a try then.

**Comment by Thermatix** [comment]
I'm sorry for the late response but I'm no longer running KISS, switched to regolith, KISS, as amazing as it is was just too much effort when I wanted something workable.

So you can close this issue if you want to.

**Comment by pragmatrix** [comment]
Thank you for updating this issue. Closing as suggested.
