### ISSUE TITLE
surface to &[u8]

### ISSUE THREAD

**Issue by konstare** [rust-skia/rust-skia#503]
Hi, 

I am new to rust and have never used skia so maybe my question is trivial. Sorry for this.
How to get &[u8] from surface? 
I am drawing on a surface and want to feed the result to ffmpeg, which accepts array of bytes. After some thinking i did something like this:

```rust

pub struct Scene {
    surface: Surface, //skia_safe::Surface
    size: ISize, //size of surface
}

impl Scene{
pub fn data(&mut self) -> Option<&[u8]> {
        use std::convert::TryInto;
        let pixmap_ptr = self.surface.peek_pixels()?;
        let pixmap_ptr = unsafe { pixmap_ptr.addr() };
        let data = std::ptr::slice_from_raw_parts(
            pixmap_ptr,
            (self.size.area() * 4)
                .try_into()
                .expect("The size of the surface is too big"),
        ) as *const [u8];
        let data = unsafe { &*data };
        Some(data)
    }
}
```

It works. But it uses a lot of unsafe code, which i bet i screwed up. How to do this properly?

**Comment by pragmatrix** [comment]
Hi, the looks fine to me. For the slice length, you should use the information that comes with `Pixmap::image_info()`, like `ImageInfo::compute_byte_size()`.

See also #441

**Comment by konstare** [comment]
Ok, with compute_byte_size it looks better. It is pity that the surface(pixmap) implementation does not have something like this.

```rust
pub fn data(&mut self) -> Option<&[u8]> {
        use std::ptr::slice_from_raw_parts;
        let pixmap_ptr = self.peek_pixels()?;
        let size = pixmap_ptr.compute_byte_size();
        let pixmap_ptr = unsafe { pixmap_ptr.addr() };
        let data = slice_from_raw_parts(pixmap_ptr, size) as *const [u8];
        let data = unsafe { &*data };
        Some(data)
    }
```

**Comment by pragmatrix** [comment]
I've tried to implement a _supposedly_ safe way to access the pixels. I would very much appreciate if you could take a closer look at #504.

**Comment by pragmatrix** [comment]
I've revised the PR. There are now to functions, `Pixmap::bytes()` returns a byte slice and `Pixmap::pixels()` returns a pixel slice.

**Comment by konstare** [comment]
>I would very much appreciate if you could take a closer look at

Sorry, i cannot figure out how to install with cargo skia-safe with your pull request. What should i write to Cargo.toml?

```
[dependencies]
skia-safe = {git = "https://github.com/rust-skia/rust-skia.git@access-pixels-safe"}
```

**Comment by pragmatrix** [comment]
It's now in master, so 
```toml
skia-safe = { git = "https://github.com/rust-skia/rust-skia.git" }
```

should work.

**Comment by konstare** [comment]
Thank you it works.
