### ISSUE TITLE
[Docs] Example for running rust-skia powered application on web env (as a good demo)

### ISSUE THREAD

**Issue by softmarshmallow** [rust-skia/rust-skia#509]
This will definitely show what things can be built with this package and bring web developers' interest into it.
+ I'm looking forward for this demo too :)

**Comment by pragmatrix** [comment]
There are a number of Rust alternatives already available, running on NodeJS there are two I know

- https://github.com/samizdatco/skia-canvas 
- https://github.com/Brooooooklyn/canvas

and for the browser

- https://skia.org/docs/user/modules/canvaskit/

for which Rust bindings could probably be created with https://github.com/rustwasm/wasm-bindgen

This project's primary goal is to run Skia on native platforms. Nevertheless, I would be delighted to make this work and community interest seems to be there (#39).

**Comment by pragmatrix** [comment]
WebAssembly is supported with the `wasm32-unknown-emscripten` target and there is a simple example in the repository:  https://github.com/rust-skia/rust-skia/tree/master/wasm-example

Closing.
