### ISSUE TITLE
Consistent Segfault loading `eglGetCurrentDisplay` using `new_load_with`

### ISSUE THREAD

**Issue by j4qfrost** [rust-skia/rust-skia#511]
I was able to avoid the segfault on neovide building for OpenGL by skipping loading the function pointer for eglGetCurrentDirectory. https://github.com/Kethku/neovide/issues/491#issuecomment-830763537 I'm not sure if this is a driver issue. Everyone who compiles up to this point hits the segfault every time. I think @Kethku might be building the opengl branch of neovide on a Windows machine, otherwise all the users should be on Linux machines. At first I thought the function pointer didn't exist in whatever library was being bound. I think there might also be a possibility that two function pointers with the same name are being looked up and so the sizes aren't matching up. This looks suspicious https://github.com/google/skia/blob/master/src/gpu/gl/GrGLAssembleHelpers.cpp

I am kind of lost as to how to investigate further. For now this hack to avoid looking up `eglGetCurrentDisplay` seems sufficient:
```
if name == "eglGetCurrentDisplay" {
    return std::ptr::null();
}
```

**Comment by pragmatrix** [comment]
Hmm, this has something to do with the GLFW setup. Flutter [had the same problem](https://github.com/flutter/flutter/issues/47954), posted it [to the Skia bugtracker](https://bugs.chromium.org/p/skia/issues/detail?id=9967) but finally fixed it [here](https://github.com/flutter/engine/pull/16924/files).

**Comment by pragmatrix** [comment]
For the record:

```
hread 1 "neovide" received signal SIGSEGV, Segmentation fault.
0x0000555556523a13 in GrGLExtensions::init(GrGLStandard, GrGLFunction<unsigned char const* (unsigned int)>, GrGLFunction<unsigned char const* (unsigned int, unsigned int)>, GrGLFunction<void (unsigned int, int*)>, GrGLFunction<char const* (void*, int)>, void*) ()
(gdb) bt
#0  0x0000555556523a13 in GrGLExtensions::init(GrGLStandard, GrGLFunction<unsigned char const* (unsigned int)>, GrGLFunction<unsigned char const* (unsigned int, unsigned int)>, GrGLFunction<void (unsigned int, int*)>, GrGLFunction<char const* (void*, int)>, void*) ()
#1  0x0000555556734f61 in GrGLMakeAssembledGLInterface(void*, void (*(*)(void*, char const*))()) ()
#2  0x00005555566b7b20 in GrGLMakeAssembledInterface(void*, void (*(*)(void*, char const*))()) ()
#3  0x00005555565a02f5 in C_GrGLInterface_MakeAssembledInterface ()
#4  0x0000555555767708 in skia_safe::gpu::gl::interface::<impl skia_safe::prelude::RCHandle<skia_bindings::bindings::GrGLInterface>>::new_load_with (load_fn=...)
    at /home/armin/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-safe-0.39.1/src/gpu/gl/interface.rs:24
#5  0x00005555557b17b4 in neovide::window::window_wrapper::renderer::SkiaRenderer::new (
    windowed_context=0x7fffffffaef0) at /home/armin/dev/neovide/src/window/window_wrapper/renderer.rs:53
#6  0x00005555557dc7ae in neovide::window::window_wrapper::start_loop (window_command_receiver=..., 
    ui_command_sender=..., running=..., logical_size=..., renderer=...)
    at /home/armin/dev/neovide/src/window/window_wrapper/mod.rs:440
#7  0x00005555557fa2dd in neovide::window::create_window (batched_draw_command_receiver=..., 
    window_command_receiver=..., ui_command_sender=..., running=...)
    at /home/armin/dev/neovide/src/window/mod.rs:106
#8  0x00005555557254d8 in neovide::main () at /home/armin/dev/neovide/src/main.rs:181

```

**Comment by j4qfrost** [comment]
I think we can close this issue here. It should be raised with glutin. I
dove into their implementation and unless loading for glx fails, an egl
context doesn't get loaded.

**Comment by pragmatrix** [comment]
Thank you for the feedback, closing.
