### ISSUE TITLE
Create a Logo for the Organization and the Library

### ISSUE THREAD

**Issue by pragmatrix** [rust-skia/rust-skia#53]
A simple one would be to take the ["rusty" Rust logo](https://www.rust-lang.org/logos/rust-logo-512x512.png), remove the R from inside the gear and put the [Skia Logo](https://en.wikipedia.org/wiki/File:Skia_Project_Logo.svg) inside.

The Rust logo is licensed under Creative Commons and can be modified, but the licensing conditions of the Skia Logo seems unclear.

**Comment by Brooooooklyn** [comment]
@SuneBear could you help us with logo if you had time?

**Comment by pragmatrix** [comment]
Thanks to @AlbertoGP who designed an icon and rendered it [with skia-safe](https://github.com/rust-skia/rust-skia/blob/master/skia-safe/examples/icon/main.rs) and a [demo animation](https://matracas.org/tmp/rust-skia-icon.html), this issue can be closed now.
