### ISSUE TITLE
Precompiled mac binaries require macOS 10.15 or later

### ISSUE THREAD

**Issue by samizdatco** [rust-skia/rust-skia#538]
I've been trying to get my `rust-skia`-derived library to run on older versions of macOS but have run into the problem that the prebuilt binaries were compiled with a deployment target of 10.15. It looks like this group has had success compiling Skia with a much broader range of target systems: https://github.com/fonttools/skia-builder/commit/3641fe7145f6cf6cd460bba7518ba851811c4405

Is there any chance the build script could set the `MACOSX_DEPLOYMENT_TARGET` env var to something older? Even `10.13` (2017) or `10.12` (2016) would be a significant increase in the number of systems the library would run on.

**Comment by pragmatrix** [comment]
@samizdatco I did not know about `MACOSX_DEPLOYMENT_TARGET`, the test builds inside the Skia source tree all use `10.13`, so I guess we should target that for the next release of the binaries? Also, we are already setting minimum iOS versions, so it could be only a matter of specifying `-mmacosx-version-min` to the compiler. I'll take a look with `otool` to see if that works and then adjust the CI jobs accordingly.

**Comment by pragmatrix** [comment]
With feature "metal" enabled, I wasn't able to go below `10.14` in #539, but all other configurations work well with `10.13`.
