### ISSUE TITLE
32bit binaries (at least windows)

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [rust-skia/rust-skia#540]
can you provide those?

**Comment by pragmatrix** [comment]
Yes, but they need to be generated with the nightly compiler, 32-bit Windows bindings need to use `thiscall` calling convention, which isn't stable yet (https://github.com/rust-lang/rust-bindgen/issues/1739, https://github.com/rust-lang/rust/issues/42202).

Would you mind sharing why you need 32-bit Windows binaries?

**Comment by MyTDT-Mysoft** [comment]
well, for one my windows 7 here is 32bit, which is good for me, since i give support to some legacy software that requires ntvdm (which i could do on a VM alright so thats just the weak part of the reason :P)... on windows i'm against using 64bit software without need (and the need for 64bit software is almost 0 when you dont write bloated programs), so i'm experimenting with this, but i want to keep my standards :)

**Comment by pragmatrix** [comment]
> i got a friend compiling skia for 32bit and i'm using the regular "C skia" interface

Ok, then you don't need the 32-bit binaries anymore from this project? 

I am asking, because if we begin to support 32-bit binaries, we will build several feature configurations for each release and perhaps one for every commit to this repository introducing a considerable long term cost in maintenance and CPU resources.

**Comment by MyTDT-Mysoft** [comment]
well, i still would say that it would be good to keep a windows 32-bit binaries at least, but if you think its a hassle to mantain, i dont want to bother you guys, you were kind enough to consider the option :)

**Comment by pragmatrix** [comment]
#541 added support for building rust-skia on Windows 32-bit targets with the nightly Rust compiler. I'll keep this issue open for a while to see if there are more people interested in binary builds.

**Comment by pragmatrix** [comment]
Closing. I am happy to reopen this if someone requires 32 bit binaries with sufficient justification, or any other platform / feature-set combination for that matter.
