### ISSUE TITLE
icu::init panics on Windows unless run as Administrator

### ISSUE THREAD

**Issue by samizdatco** [rust-skia/rust-skia#557]
When the `textlayout` feature is enabled on Windows, my understanding is that client code should call `icu::init()` before attempting to do any typesetting so it can extract the `icudtl.dat` data and write it to disk. Skia itself seems to [strongly prefer](https://github.com/google/skia/blob/eb0195e5b4d5d61dfa97483c15e519b56c6a1a98/third_party/icu/SkLoadICU.cpp#L103) that it live in the same directory as the current executable (though it will also look in the library’s directory after printing a somewhat misleading error message suggesting it failed).

The current `icu::init` behavior of ensuring `icudtl.dat` is in the executable dir (and [panicking](https://github.com/rust-skia/rust-skia/blob/71c4728704abb4394077d5ea1b9faaf5c2ad5797/skia-bindings/src/icu.rs#L14-L15) if it's unable to create it) is causing [problems](https://github.com/samizdatco/skia-canvas/issues/35) for my Node library since in this case the executable is Node itself which lives in "Program Files" and thus requires Administrator access to modify.

It seems like the ideal solution would be to merge pull request #486 and dispense with the external file altogether. Is there anything currently blocking this that I could help out with? Alternatively, could `icu::init` check for the data file in the library directory as well before exiting?

**Comment by pragmatrix** [comment]
> my understanding is that client code should call icu::init() before attempting to do any typesetting so it can extract the icudtl.dat data and write it to disk

correct.

> Is there anything currently blocking this that I could help out with?

The problem with the #486 is that it modifies Skia [even more](https://github.com/rust-skia/skia/compare/6f919cdb58eee29bb84c096d250d7aedabd96325...794a98b1721269a7f33ea4eabf57f5dabc40c862), which makes it harder to configure rust-skia with local / external Skia builds.

To finish this PR I the functionality (specifically the requirement to link to `C_SetICU`) should be hidden behind a feature flag which may be added to the list of default features.

> Alternatively, could icu::init check for the data file in the library directory as well before exiting?

I think this the best option to get this fixed as soon as possible.

**Comment by pragmatrix** [comment]
> Alternatively, could icu::init check for the data file in the library directory as well before exiting?

@samizdatco It is [already checked for](https://github.com/rust-skia/rust-skia/blob/master/skia-bindings/src/icu.rs#L10), so it should be possible to just copy `icudtl.dat` to the target directory in the installation process on Windows. Will this work for you?

**Comment by pragmatrix** [comment]
I suspect from scanning over the issues referring to #486 that this is something hard to work around for. I'll try to refurbish the PR and see if we can hide the functionality behind a feature flag.
