### ISSUE TITLE
icudtl.dat still causing panic

### ISSUE THREAD

**Issue by buzmeg** [rust-skia/rust-skia#559]
I see that #557 is closed, but just today I got:

SkIcuLoader: datafile missing: C:\Users\username\project\target\debug\icudtl.dat.
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\username\.cargo\registry\src\github.com-1ecc6299db9ec823\skia-safe-0.41.0\src\modules\paragraph\paragraph_builder.rs:70:10

This is on Windows 10 with:
stable-x86_64-pc-windows-msvc (default)
rustc 1.54.0 (a178d0322 2021-07-26)

Thanks.

**Comment by pragmatrix** [comment]
This was scheduled to be included with the [0.42.0 Update (Milestone 93)](https://github.com/rust-skia/rust-skia/releases/tag/0.42.0) which was released to crates.io just now. Closing. Please reopen if the problem reappears with 0.42.0.
