### ISSUE TITLE
FreeType 2.7+ required as of release 0.43.0?

### ISSUE THREAD

**Issue by samizdatco** [rust-skia/rust-skia#570]
It seems that a more recent version of FreeType was used for the last round of precompiled binaries which includes a call to `FT_Set_Default_Properties`. This function isn't present in versions of FreeType prior to 2.7 and is causing undefined symbol errors when run on older linux systems (in particular Debian Stretch which is still quite popular for use in Docker containers).

I'm unsure whether anything can/should be done to try to preserve backward compatibility or if this is under the control of `skia/third_party/freetype2` and we should adjust the system requirements accordingly. What do you think?

**Comment by samizdatco** [comment]
After looking over some of what's been added to freetype since 2.6 (support for variable fonts, type 1, and woff formats) it seems like it would be a mistake not to use the most up-to-date version possible, even on older systems.

I tried disabling the `skia_use_system_freetype2` option as you suggested and everything seems to work great from the perspective of the js code that's calling into the library. The only surprise in getting it to compile on Stretch was needing to use the `stretch-backports` apt source in order to get a recent enough version (5.0) of llvm to handle Skia's c++17-isms.

For my use-case I don't expect any other code to be linking against my dylib so the possibility of the linker mixing the embedded freetype and system freetype code shouldn't be a problem. For `skia-safe`, though, I'm less sure that it makes sense to add an `embed-freetype` feature due to the risk of conflicts. It's hard to know whether it would cause more trouble for users than the backward compatibility is worth…

**Comment by pragmatrix** [comment]
To conclude that, I've added a Dockerfile for Debian 9 ("stretch") to the repository and also a non-default feature `embed-freetype` in #575.
