### ISSUE TITLE
M1 iOS simulator building fails

### ISSUE THREAD

**Issue by triniwiz** [rust-skia/rust-skia#574]
I'm trying to build for the m1 ios simulator with `cargo build --target aarch64-apple-ios-sim -vv` from a clone but I get the following error.

```bash
(libskia.SkDocument.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
```

So if build it in my project it builds fine, but trying to build it into an archive with xcode throws the same error .. Any suggests would be great .. thanks

**Comment by triniwiz** [comment]
Tried a couple more things , updated cc to get [this](https://github.com/alexcrichton/cc-rs/pull/614) then updated the config to set `-arch arm64` . While building I get the following log  along with the initial error .
```bash
warning: clang: warning: argument unused during compilation: '-arch arm64' [-Wunused-command-line-argument]
```

**Comment by triniwiz** [comment]
I got it working if I set the `target_str` as `"--target=arm64-apple-ios14.0.0-simulator"`

**Comment by pragmatrix** [comment]
M1 iOS simulator builds should work now. See #629 for all the details and the PR #631. Thank you @triniwiz for helping out.
