### ISSUE TITLE
Streaming PDFs

### ISSUE THREAD

**Issue by giacomocariello** [rust-skia/rust-skia#584]
In PDF generation, it would be nice to be able to stream output, possibly asynchronously, instead of getting final byte array after close(). Would it be possible to expose self.stream's DynamicMemoryWStream in some way?

**Comment by pragmatrix** [comment]
It's not possible yet, but a good idea. As soon #569 gets merged, we will be able to interface with the `io::Read` trait. So I guess it should be possible to add a C++ class `RustWStream` in the same vain that writes to a type that implements the `io::Write` trait.
