### ISSUE TITLE
Resize jitter in gl-window example

### ISSUE THREAD

**Issue by warrd** [rust-skia/rust-skia#587]
I have been following the gl-window example to integrate `rust-skia` into my desktop application and have noticed there is sometimes jitter in the rendered output when resizing the window (X11), which happens when the rendering code is slow.

I have created a fork with the [following change](https://github.com/warrd/rust-skia/commit/cf085f0692cdbb8ce8469b89deefbc780bb74d53) to show what I mean: 
```rs
            Event::RedrawRequested(_) => {
                {
                    let canvas = env.surface.canvas();
                    canvas.clear(Color::WHITE);

                    let rect = skia_safe::Rect { left: 0.0, top: 0.0, right: 600.0, bottom: 600.0 };
                    let mut paint = skia_safe::Paint::default();
                    paint.set_color(Color::BLACK);
                    canvas.draw_rect(rect, &paint);

                    // Simulate slow render computation
                    std::thread::sleep(std::time::Duration::from_millis(50));
                }
                env.surface.canvas().flush();
                env.windowed_context.swap_buffers().unwrap();
```

When the window is resized the rendered quad is not in the correct `y` position at first, and jitters up and down (interestingly the `x` position is not affected). I was under the assumption that setting up gl with double buffering should avoid such issues, but apparently not in this case.

Would be interested to hear whether you have any ideas about what is responsible for this. I am not quite sure whether this is an issue with the example itself, `rust-skia`, `glutin` or `winit`, so happy to take the discussion elsewhere if you think this is the wrong place.

Thanks

**Comment by pragmatrix** [comment]
I've run the gl-window example in your branch on Windows, macOS and in a Ubuntu VM. And the positioning error happens only on X11. I suspect that when a swap chain image is rendered with an incorrect size, it is centered vertically in the containing window. I had a similar effect when I was rendering using Vulkan on Windows, where the image got scaled resulting in a very disturbing wobbling effect while resizing. I switched to DirectX because of that and some other reasons where I was able to configure these behaviors in detail. Doubting that this is something related to this project or Skia itself, I'd suggest you to look deeper in the flags you can provide in the swap chain creation in glutin to see if this behavior can be changed.

**Comment by ctrlcctrlv** [comment]
Is it OK in Wayland, I wonder?

**Comment by pragmatrix** [comment]
Yes, the rectangle does not move while resizing on wayland, but I had to remove the line that enables double buffering, probably because the compositor is already taking care of that.

**Comment by warrd** [comment]
Thanks for testing this on different platforms! You are probably right unlikely related to skia itself or these bindings, next week sometime I will try looking at the swap chain flags, and if no luck will produce a minimal example using glutin directly which reproduces the issue. Will update this thread if I find anything.

**Comment by pragmatrix** [comment]
Stale issue, closing.

**Comment by bmitc** [comment]
Hi @warrd! Did you ever figure this out? I am using my own bindings to GLFW in F# and SkiaSharp for rendering, and I am seeing a very similar issue. I cannot figure this out and saw that you had a very similar problem. Interestingly enough, I also see this mainly in the vertical direction. But I also see it horizontally sometimes as well. It's just that the vertical direction is more frequent. It's very confusing.
