### ISSUE TITLE
Add a canvas-like API

### ISSUE THREAD

**Issue by Milo123459** [rust-skia/rust-skia#589]
Coming from web development, it'd be nice to have a canvas-like API in this project, powered by skia.

**Comment by ctrlcctrlv** [comment]
Can you please explain what you mean? There's a `&mut Canvas` based on SkCanvas. Take a look at MFEKglif maybe for a project with a lot of example code using rust-skia…see e.g. https://github.com/MFEK/glifrenderer.rlib/blob/a7ffb0bab075963c474c15e089180bcb928dde39/src/points/mod.rs#L100 for an example of using the canvas API to draw a triangle.

**Comment by Milo123459** [comment]
The canvas web api: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API

**Comment by ctrlcctrlv** [comment]
How would that work in Rust…?

**Comment by ctrlcctrlv** [comment]
A lot of the functions are already very Canvas API-like. Although my projects typically do not do this, preferring to create SkPath's outside of the SkCanvas and then draw them all in one go, it is possible to call functions like `Canvas::draw_point`, `Canvas::draw_rect`, `Canvas::draw_oval`…there is even `Canvas::draw_str` (again, my projects aren't a good example of this as I prefer to, for reasons of performance, cache my `TextBlob`'s and draw them, but you don't need to do it this way).

**Comment by meihuanyu** [comment]
i think you want https://github.com/samizdatco/skia-canvas

**Comment by pragmatrix** [comment]
I am closing this, as being out of scope for this project. This project focuses on bringing Skia to the Rust ecosystem. An API in Rust that looks similar to the [Web Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) should be fairly simple to create based on the wrappers rust-skia provides, and Canvas like APIs that use rust-skia as backend were created in other projects already like [Skia-Canvas](https://github.com/samizdatco/skia-canvas), although I am not sure if they can be used from Rust.
