### ISSUE TITLE
When setting SKIA_SOURCE_DIR on Windows the build script fails to find python2.

### ISSUE THREAD

**Issue by MatthewBlanchard** [rust-skia/rust-skia#598]
I'm trying to get a local copy of Skia building with this library on Windows, but I'm unable to do so because the build script fails to find python2. I have both Python3 and Python2 in PATH as "python" and "python2" respectively.

```
  Probing 'python'
  Probing 'python2'

  --- stderr
  Checking for "C:\\Program Files\\LLVM\\bin\\clang-cl.exe"
  thread 'main' panicked at '>>>>> Probing for Python 2 failed, please make sure that it's available in PATH, probed executables are: ["python", "python2"] <<<<<', C:\Users\matth\.cargo\registry\src\github.com-1ecc6299db9ec823\skia-bindings-0.39.1\build_support\skia.rs:1332:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
C:\Users\matth\Documents\GitHub\MFEKglif (tool_refactor -> upstream)
λ python2
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

The above is the output of python2 on my system. I'm using a terminal emulator Cmder here, but I've checked to make sure python2 is in the path for cmd as well since cmder provides some command-line tools on its own.

I've been testing my patch through a simple C++ skia project, but I'd really like to get it building for an existing Rust project I've worked on.

**Comment by pragmatrix** [comment]
I'm not sure why `SKIA_SOURCE_DIR` should affect the Python resolver. Can you try the Python 3 branch in #595?

**Comment by ctrlcctrlv** [comment]
MFEKglif has a file `.cargo/config.toml` which sets some env vars:

https://github.com/MFEK/glif/blob/a9eebbd1348fea107b9b33d0ceb13782eafe8899/.cargo/config.toml#L4-L5

I wonder if you could set PATH in here as a workaround :thinking: 

This file should only be additive, and not replace the env, so it shouldn't be the issue.

**Comment by ctrlcctrlv** [comment]
Also, what if you try the build in `MSYS2`, that would be my first two things to try, because in `MSYS2` you would have bash and could therefore set environment in the way the Makefile expects:

https://github.com/MFEK/glif/blob/a9eebbd1348fea107b9b33d0ceb13782eafe8899/Makefile#L27

**Comment by pragmatrix** [comment]
Closing, as we moved to Python3 recently and I don't see anything actionable here.
