### ISSUE TITLE
encode image None

### ISSUE THREAD

**Issue by meihuanyu** [rust-skia/rust-skia#603]
```rust
let bytes = include_bytes!("b.png");
let data = Data::new_copy(bytes);
Image::from_encoded(data)

```

[b.png.zip](https://github.com/rust-skia/rust-skia/files/7821745/b.png.zip)

**Comment by ctrlcctrlv** [comment]
Do you get the same result with the C++ API?

(Image doesn't load for me. If you want to be sure GitHub won't mangle any of its bytes, put it in a zip archive and upload that.)

**Comment by meihuanyu** [comment]
sorry, I re upload zip.
I'm not familiar with C++, I'll try C++ today.

**Comment by ctrlcctrlv** [comment]
Yes, try the C++ Skia API (SkImage). If that also cannot encode the image, you should close this issue and open one upstream.

**Comment by ctrlcctrlv** [comment]
However, if C++ _can_ do it, then it's a Rust issue, so come back here and say so…

**Comment by meihuanyu** [comment]
C++ can't be opened.
The reason is that the picture chunck data too large.
libpng default limit chunck data 8092 bytes.
