### ISSUE TITLE
Black screen when using Metal with 0.45.1

### ISSUE THREAD

**Issue by terhechte** [rust-skia/rust-skia#609]
Hey, I'm trying to run skia with winit and metal. I found [this PR in a repo here](https://github.com/fzzr-/rust-skia-metal-window/pull/1) and it works great. However this version is using rust-skia 0.38. When I update it to 0.45 it still compiles but the screen stays black. I'm probably doing something wrong but my knowledge about GPUs and Metal is too limited to figure out how to fix this.

I tried to look at the [drivers](https://github.com/rust-skia/rust-skia/blob/master/skia-org/src/drivers/metal.rs) example but that just writes to disk and doesn't run a winit event loop.

I also looked at the [gl-window](https://github.com/rust-skia/rust-skia/blob/master/skia-safe/examples/gl-window/main.rs) example but that uses OpenGL and I couldn't see anything that would help me fix my metal issue.

**Comment by pragmatrix** [comment]
The example project uses a wrong sample count 4. With a sample count 1, the example seems to work fine: https://github.com/pragmatrix/rust-skia-metal-window/commit/761c99399e77165d4aafd9ec60c9a84a7b291d44

Hope this gets you started. I've also updated most of the dependencies (winit, metal-rs) in my fork.

**Comment by terhechte** [comment]
thank you! I'll give it a try
