### ISSUE TITLE
clang-sys = "=1.0.1"  breaks my build

### ISSUE THREAD

**Issue by Dushistov** [rust-skia/rust-skia#627]
After several hour of investigation I found culprit that cause bindgen failure on macos:
  
https://github.com/rust-skia/rust-skia/blob/3d64d9727c634e01b606aa0cf30a369d9d248037/skia-bindings/Cargo.toml#L80

If I remove skia-safe my bulid on macos works just fine,
but with skia-safe bindgen gives strange error about not valid C/C++,
while it is completely valid C/C++ and standard clang can compile it without any problems.

Comparing output of `cargo tree` I found out that bindgen works with `clang-sys="1.3.1"`,
and failed with `clang-sys="1.0.1"`.

Is it possible to remove `clang-sys = "=1.0.1" ` from dependency tree of `skia-safe`.
If it CI related problem, may be just call `sed -i s/\[dependencies\]/\[dependencies\]\nclang-sys = "=1.0.1" \n/g`
during CI run?

**Comment by pragmatrix** [comment]
You are right, we should update clang-sys to the latest version and see if we can fix the CI build by removing the libclangs we can't use from the PATH.

**Comment by pragmatrix** [comment]
This went better than expected, it seems that the problem does not appear with GitHub's windows-2022 images anymore.
