### ISSUE TITLE
Provide skia-binaries for aarch64-apple-ios-sim

### ISSUE THREAD

**Issue by ln-12** [rust-skia/rust-skia#629]
As the title says, it would be awesome to have pre-built binaries for `aarch64-apple-ios-sim`. Would this be possible?

**Comment by pragmatrix** [comment]
Yes, sounds reasonable, let's see if we get the builds through the CI first (#631).

**Comment by JayTee42** [comment]
Thanks for addressing this, @pragmatrix ! You are doing great work here. Sadly, the CI pipeline appears to have failed with an error that @ln-12 and me have encountered before when we tried to build for the simulator: `[...] building for iOS Simulator, but linking in object file built for iOS, for architecture arm64`

We found [this Google Groups discussion](https://groups.google.com/g/skia-discuss/c/L94FJb4jIk0) regarding the same topic: Apparently, there is a new GN flag called `ios_use_simulator` that must be set for Skia to select the correct SDK. Hope this helps!

**Comment by triniwiz** [comment]
@JayTee42 that's interesting now it has me wondering how I managed to get it working, after editing [2 files](https://gist.github.com/triniwiz/4306ff86aa5df0a7baac4ce59ccc77f6) 😅 hopefully it can help.

**Comment by pragmatrix** [comment]
Thanks you @JayTee42 and @triniwiz. I've incorporated both of your suggestions / code:

- The `ios_use_simulator` flag isn't available in the current milestones. Although I don't think it's even needed, we'll set the flag for all simulator configuration and cherry-pick the Skia commit into our branch until it finds it way into a future milestone branch.
- Even with `ios_use_simulator=true`, the linker errors did appear. Here @triniwiz's code that modified the `--target` option to `arm64-apple-ios14.0.0-simulator` made it finally work on my Intel Mac.

Now let's see if it goes through the CI.
