### ISSUE TITLE
decode jpeg empty pixels

### ISSUE THREAD

**Issue by Jetsly** [rust-skia/rust-skia#630]
i want decode jpeg image, but get empty pixels

```rust
use std::{fs::File, io::prelude::*};

use skia_safe::{
    image::CachingHint, AlphaType, ColorType, Data, Image as SkImage, ImageInfo, Size,
};

#[test]
fn decode_jpeg() {
    let mut file = File::open("./assets/test_hc.png").expect("failed to open file");
    let mut data = Vec::new();
    file.read_to_end(&mut data).unwrap();
    let image = SkImage::from_encoded(Data::new_copy(&data)).expect("failed to decode");
    let size = Size::new(image.width() as f32, image.height() as f32).to_floor();
    let dist = ImageInfo::new(size, ColorType::RGBA8888, AlphaType::Unpremul, None);
    let min_row_bytes = dist.min_row_bytes();
    let mut buffer = vec![0u8; dist.compute_byte_size(min_row_bytes)];
    image.read_pixels(
        &dist,
        &mut buffer,
        min_row_bytes,
        (0, 0),
        CachingHint::Allow,
    );
    let part = &buffer.as_slice()[1..100];
    println!("{:?}", part);
}
```

```shell
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

![test_hc](https://user-images.githubusercontent.com/6357863/162659944-3fef8649-3a06-4944-8c28-fa13e8838ab3.jpeg)

**Comment by pragmatrix** [comment]
I am not sure what's wrong, check the return value from `read_pixels` (it returns `false`) and use the `image_info()` from the `Image` for testing to rule out that format conversions fail.  I've downloaded the picture from GitHub (as jpeg), there `read_pixels` fails, debugging `read_pixels` and the underlying C++ code exposed a decoding error, which let me believe this some kind of unsupported detail in both the PNG and JPEG ... some exotic alignment may be. Loading into Paint.net and saving it worked. Also, you may take a look at the `Codec` type from which you should be able to get a more detailed error result.

**Comment by Jetsly** [comment]
how can i catch this error

**Comment by Jetsly** [comment]
how can i catch error,i use `Codec` is normal
```
  let mut code = Codec::from_data(Data::new_copy(&data)).unwrap();
    println!("{:?} {:?}", code, code.info());
    let dist = code.info();
    let min_row_bytes = dist.min_row_bytes();
    let mut buffer = vec![0u8; dist.compute_byte_size(min_row_bytes)];
    code.get_pixels_with_options(&dist, &mut buffer, min_row_bytes, None);
```

**Comment by ctrlcctrlv** [comment]
Cute image, and not saying it's an issue for me and my furry profile image, but in future please zip such images out of respect to people who might be at work or who have installed spying software by their employers. Also, zipping your test images helps anyone who tries with debugging :)

**Comment by ctrlcctrlv** [comment]
Oh and @pragmatrix I don't think it's anything _that_ bizarre. I found this thread funny due to my comment so went to post it in Twitter, but it revealed a Firefox bug—the screenshot tool can't handle it. https://twitter.com/fr_brennan/status/1523872690230157313

I downloaded the file and converted it to get it to post. `convert` result:

```
convert-im6.q16: Premature end of JPEG file `162659944-3fef8649-3a06-4944-8c28-fa13e8838ab3.jpeg' @ warning/jpeg.c/JPEGWarningHandler/389.
convert-im6.q16: Corrupt JPEG data: premature end of data segment `162659944-3fef8649-3a06-4944-8c28-fa13e8838ab3.jpeg' @ warning/jpeg.c/JPEGWarningHandler/389.
```

The image is corrupt.

**Comment by pragmatrix** [comment]
@ctrlcctrlv Great investigative work! 

Closing.
