### ISSUE TITLE
Typeface creation always fails in WASM builds

### ISSUE THREAD

**Issue by tomb-msft** [rust-skia/rust-skia#648]
Creating typefaces from the FontMgr instance returned by `FontMgr::default` seems to always fail in WASM builds of skia-safe.

By default, Skia on WASM builds with FontMgrCustomEmbedded, but [this is explicitly disabled in skia-bindings](https://github.com/rust-skia/rust-skia/blob/master/skia-bindings/build_support/skia/config.rs#L240) due to a missing symbol (`SK_EMBEDDED_FONTS`) so it uses SkEmptyFontMgr instead, which always fails. Skia seems to [generate this automatically](https://github.com/google/skia/tree/1f193df9b393d50da39570dab77a0bb5d28ec8ef/modules/canvaskit/fonts) to bundle Noto Mono in CanvasKit.

There's also the alternative FontMgrCustomEmpty (under `skia_enable_fontmgr_custom_empty`) which seems to work the same as the embedded font manager but without requiring any preloaded fonts. Enabling this makes typeface creation work.

I'm happy to put up a PR to fix this, but which option do you think makes the most sense? Personally I'd prefer to avoid bundling a font, but FontMgrCustomEmbedded might be convenient since it matches CanvasKit's behaviour.

**Comment by pragmatrix** [comment]
> I'm happy to put up a PR to fix this, but which option do you think makes the most sense?

I'm not using WASM at the moment, so whatever fits your usecase is probably a good move forward fixing this as long no other party objects or has better ideas.
