### ISSUE TITLE
Crates.io `0.51.0` release

### ISSUE THREAD

**Issue by MultisampledNight** [rust-skia/rust-skia#661]
Coming from https://github.com/neovide/neovide/pull/1413, there has been some confusion about whether `python2` is required or not. From what I understood in #595, `0.51.0` should include the Python 3 switch, which would be nice to have (then we can also be explicit about needing Python 3 for building Neovide), but is not on crates.io yet (last release at time of writing is `0.50.0`). Would it be possibe to push a release on the then-new state of `0.51.0` or even newer now?

Also by the way, the `updates to Chrome stable` in CONTRIBUTING.md is a 404, perhaps you meant to link to https://chromestatus.com/roadmap now.

**Comment by pragmatrix** [comment]
Yes, of course. I'm preparing a new release from master `0.52.0`. And thanks for reporting the broken link.

**Comment by pragmatrix** [comment]
`0.52.0` skia-bindings and skia-safe crates got published to crates.io. Tag: https://github.com/rust-skia/rust-skia/releases/tag/0.52.0.

**Comment by MultisampledNight** [comment]
Thank you!
