### ISSUE TITLE
Returned 127 when attempting to build for Alpine x86_64 (x86_64-unknown-linux-musl)

### ISSUE THREAD

**Issue by peter-marshall5** [rust-skia/rust-skia#666]
Building this crate on Alpine Linux does not succeed.

Below is the output of the command: `cd skia-bindings; RUST_BACKTRACE=full cargo build --release >build.log 2>>build.log`
[build.log](https://github.com/rust-skia/rust-skia/files/9215196/build.log)

**Comment by pragmatrix** [comment]
A file seems missing from the `skia/third_party/externals` directory. Can you check if the file `/skia-bindings/skia/third_party/externals/libgifcodec/libgifcodec.gni` exists. It should be made available in the Synchronizing "Skia dependencies" step.

**Comment by peter-marshall5** [comment]
The file `skia-bindings/skia/third_party/externals/libgifcodec/libgifcodec.gni` does in fact exist.
Interestingly, `cd`ing to the directory listed in `Current dir` and manually running the Python command that fails during the build returns `True` with an exit code of `0`.

**Comment by peter-marshall5** [comment]
It's now working with the latest release tag.

**Comment by pragmatrix** [comment]
Thank you for the feedback. It's probably because the Skia team removed libgifcodec in favor of [wuffs](https://github.com/google/wuffs) in a recent milestone update.
