### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by mohe2015** [rust-skia/rust-skia#674]
Hello,

it seems like the current version is [0.53.0](https://github.com/rust-skia/rust-skia/releases/tag/0.53.0) but https://rust-skia.github.io/doc/skia_safe/ is still at 0.34.0

Would it be possible to update that?

Kind regards
Moritz

**Comment by pragmatrix** [comment]
Thank you Moritz a lot. The script generating the documentation copied it to the `doc/doc` subdirectory instead of `doc`. Fixed in ad6e8458e3886cd37ba91420ea37f99fc0acc8a8. Documentation should now based on what's in the current master branch.
