### ISSUE TITLE
Support proxies to download skia libs

### ISSUE THREAD

**Issue by jupyterkat** [rust-skia/rust-skia#691]
preferably using HTTP_PROXY/HTTPS_PROXY envvars

**Comment by jupyterkat** [comment]
#644

**Comment by Tim-Paik** [comment]
I thought maybe it would be better to mention this in the readme or docs?  To prevent someone from having similar problems again

**Comment by pragmatrix** [comment]
Since we use curl since a few releases ago for downloading binaries and skia sources, the env vars HTTP_PROXY and HTTPS_PROXY should work now. Closing.
