### ISSUE TITLE
Build error when building for Android on Windows Host

### ISSUE THREAD

**Issue by Hpmason** [rust-skia/rust-skia#695]
When building for Android, on Windows, `skia-bindings` generates the following error:
```
error: no such file or directory: '/std:c++17'
```
https://github.com/rust-skia/rust-skia/blob/53d47ef15b40d9aeec22c2d635f0107974f01eae/skia-bindings/build_support/skia_bindgen.rs#L204-L207
Problem is, the host system is Windows, so `cfg!(windows)` is still true, but the clang++ compiler provided by the Android NDK does like that. We could use the env var set by cargo "CARGO_CFG_TARGET_OS" and check if it's "windows". 
```rust
let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap();
if target_os == "windows" {
    // Use windows flag
}
```
Though, I don't know if there are any other compilers on Windows that would be affected by this change.

**Comment by pragmatrix** [comment]
You are right, this looks wrong, in this context, the flag `/std:c++17` should only be set when the msvc compiler builds the target. I'll prepare a fix.
