### ISSUE TITLE
NDK sysroot in different location for versions >=22

### ISSUE THREAD

**Issue by Hpmason** [rust-skia/rust-skia#697]
For NDK versions >=22, sysroot is no longer in the NDK root directory. sysroot is now under the directory `$NDK/toolchains/llvm/prebuilt/$HOST_TAG` (i.e. for Windows: `Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64`). I also had to remove the "-isystem" flag for the newer versions to compile.

I have a working [branch](https://github.com/Hpmason/rust-skia/tree/support-newer-ndk). I've tested NDK version 21-25 it on Windows and Ubuntu WSL using [cargo apk](https://github.com/rust-windowing/android-ndk-rs) and it all compiles successfully.

**Comment by pragmatrix** [comment]
This looks great. Would you mind opening a PR? I'll try to see if I can update the Android build configurations on the CI based on your changes.

**Comment by pragmatrix** [comment]
Landed with #701!
