### ISSUE TITLE
Support SVG prebuilt binaries

### ISSUE THREAD

**Issue by marc2332** [rust-skia/rust-skia#706]
Hey!

First of all, thank you for making Rusty bindings for Skia, this is wonderful!

I am currently working on [Freya](https://github.com/marc2332/freya), a GUI library for rust that renders using this project.
I would like to include SVG support, but sadly there are no SVG-supported prebuilt binaries as far I can see in [here](https://github.com/rust-skia/skia-binaries/releases/tag/0.55.0). So, when I enable the SVG feature it starts compiling Skia on its own, which I find quite frustrating since my library should be easy to use.

So, would it be possible to also make prebuilt binaries using SVG? I have made some tests on my [own repo](https://github.com/marc2332/rust-skia/releases/tag/0.54.0), but I was only able to make it work for Windows, I tried for Linux but didn't go well.

Thoughts?

**Comment by pragmatrix** [comment]
And also note that SVG rendering support is experimental and Skia's support felt incomplete the last time I used it, so you might be interested to look for alternatives in the long run.

**Comment by marc2332** [comment]
> Hello!
> 
> I have a some ideas on how to limit this exponential explosion of feature combinations, but until that gets fleshed out, I will add all the binaries you need. From what I've seen in your repository, you currently use `gl,textlayout` as a basis. So which Platforms do you target your library at right now? Currently, we support three categories. These are Web (wasm), Desktop (linux, macos, windows), and Mobile (android, ios).

Hey! I appreciate this!
For now I plan to only support Desktop, with these combinations should be enough for now:
- Windows: `gl, textlayout, svg`
- MacOS: `gl, textlayout, svg`
- Linux: `gl, textlayout, svg, x11`

Thank you! :pray:

**Comment by marc2332** [comment]
> And also note that SVG rendering support is experimental and Skia's support felt incomplete the last time I used it, so you might be interested to look for alternatives in the long run.

That's interesting to know, do you know other alternatives I could use?

**Comment by pragmatrix** [comment]
https://github.com/RazrFalcon/resvg, Somewhere buried deep in GitHub you'll may find an older rust-skia backend and I would be _very much_ interested in an up to date backend for rust-skia and would also offer to maintain it.

**Comment by trickypr** [comment]
I am pretty sure that `resvg` uses `tiny-skia`.
> `tiny-skia` should be viewed as a Rust 2D rendering library that uses Skia algorithms internally. We have a completely different public API. The internals are also extremely simplified. But all the core logic and math is borrowed from Skia. Hence the name.

Porting `resvg` to skia might be more painful than passing svgs through a simplification tool (like [`usvg`](https://github.com/RazrFalcon/resvg/tree/master/usvg)) before rendering them.
