### ISSUE TITLE
API Design - The Rect type is very confusing

### ISSUE THREAD

**Issue by colbyn** [rust-skia/rust-skia#718]
### Discussed in https://github.com/rust-skia/rust-skia/discussions/717

<div type='discussions-op-text'>

<sup>Originally posted by **colbyn** October 27, 2022</sup>
The `Rect` type is very confusing, for instance:
- What corner does `Rect::left` and `Rect::right` apply to? 
- Ditto for `Rect::top` and `Rect::bottom`?  

```rust
pub struct Rect {
    pub left: scalar,
    pub top: scalar,
    pub right: scalar,
    pub bottom: scalar,
}
```

Most geometry libraries seem to represent `Rect`s VIA a min and max 2D point, which is much more intuitive. </div>

**Comment by colbyn** [comment]
After I posted this to the discussion section, it seemed like the issue section would be more appropriate. Anyway if you wanna close either one its fine with me.

**Comment by tronical** [comment]
This is how Skia defines it upstream: https://api.skia.org/structSkRect.html . I'm not sure it's a good idea to deviate from that in the Rust bindings.

I suppose a binary compatible representation with two points could be done, but IMHO it's not worth it.

To answer the question: left, right, top and bottom do not apply to *corners*, they apply to *edges*. In the light of that I think it's a sensible definition.

This could be added to the docs though :)

**Comment by ctrlcctrlv** [comment]
I've never found it confusing. What would be confusing is an ad hoc implementation that deviates significantly from Skia's C++ API.

**Comment by colbyn** [comment]
Regarding
> To answer the question: left, right, top and bottom do not apply to corners, they apply to edges. In the light of that I think it's a sensible definition.

@tronical Oh that makes sense! 

And @ctrlcctrlv yeah I suppose you're right, I guess I'll close this issue.
