### ISSUE TITLE
Support to all features in a prebuilt

### ISSUE THREAD

**Issue by jorgeajimenezl** [rust-skia/rust-skia#730]
Hi
Due to the bad network environment (I'm from Cuba), it is impossible for me to compile the library for the features I want to test, I would like to know if it is possible to include a precompiled file that includes all the features.
I am currently trying to use `gl,textlayout,vulkan,x11,egl,wayland`.
I also think it would be good for people who first just want to test the library.
Thanks

**Comment by pragmatrix** [comment]
The long term plan is to _upgrade_ feature requests for the binaries if the _specific_ binary for the requested feature set is not available. Which means that for every (supported) platform there _must_ be at least one binary with the full feature set. So a first step in this direction is to provide these. And assuming you meant Linux, I will add a binary with the full feature set to the next release. 

There might be issues with feature upgrades. Features may be incompatible, skia-safe might cause linker errors when the feature combinations diverge, etc. But I'm sure we can sort them out over time. The result is, that there will be almost always a path for users to download prebuilt binaries, regardless of the actual selected features.

**Comment by jorgeajimenezl** [comment]
Yes, I meant linux when I spoke.
Thank you very much for the answer.
I look forward to the next release, meanwhile I'll play :) with the currently available binaries.
