### ISSUE TITLE
Support SVG + textlayout + gl + wayland

### ISSUE THREAD

**Issue by marc2332** [rust-skia/rust-skia#737]
Hey Armin!

I am the one from https://github.com/rust-skia/rust-skia/issues/706 :)
Would it be possible to have prebuilt binaries of Skia with the features `svg`, `textlayout`, `gl`, `wayland` and `x11` for Linux ?
Enabling both `wayland` and `x11` shouldn't be a problem, right?
I am only missing Wayland support at the moment, I would appreciate if it was also supported. 

Let me know what you think!

Thank you again :D

**Comment by pragmatrix** [comment]
Hey Marc,
I am trying to prepare a new release and added the wayland binaries in 6dadab630fbb30e2d5a71133208e8f22a880576d. Please tell me if you don't need the x11 (only) binaries anymore.

**Comment by marc2332** [comment]
> Hey Marc, I am trying to prepare a new release and added the wayland binaries in [6dadab6](https://github.com/rust-skia/rust-skia/commit/6dadab630fbb30e2d5a71133208e8f22a880576d). Please tell me if you don't need the x11 (only) binaries anymore.

Hi, `x11`-only binaries are no longer needed. I will be enabling `x11` and `wayland` at the same time!

Thank you again Armin!

**Comment by marc2332** [comment]
Hey again! I was about to try this but I don't think the binaries are actually being built, I can't seem to find a `gl, textlayout, svg, wayland, x11` combo in https://github.com/rust-skia/skia-binaries/releases/tag/0.57.0

**Comment by pragmatrix** [comment]
You are right, I've forgot to re-create the workflows, fixed in 3e3c012335c2258c0e1008475bc72cd7abb3a608. Will be available in 0.58.0 then.

**Comment by marc2332** [comment]
Thank you 😄
