### ISSUE TITLE
Sample used rust-skia 0.58.0 link build in windows

### ISSUE THREAD

**Issue by lencil** [rust-skia/rust-skia#758]
build following simple example with 0.47 works fine. but failed with 0.58
(msvc 2022 community)
[skia-test.zip](https://github.com/rust-skia/rust-skia/files/10422518/skia-test.zip)

  = note: skia.lib(skia.SkSLVMCodeGenerator.obj) : error LNK2019: unresolved external symbol __std_max_element_8 referenced in function "private: struct SkSL::`anonymous namespace'::Value __cdecl SkSL::SkVMGenerator::writeIntrinsicCall(class SkSL::FunctionCall const &)" (?writeIntrinsicCall@SkVMGenerator@SkSL@@AEAA?AUValue@?A0x6BA93B68@2@AEBVFunctionCall@2@@Z)
          skia.lib(skia.SkSLFindAndDeclareBuiltinFunctions.obj) : error LNK2019: unresolved external symbol __std_find_trivial_8 referenced in function "void __cdecl SkSL::Transform::FindAndDeclareBuiltinFunctions(struct SkSL::Program &)" (?FindAndDeclareBuiltinFunctions@Transform@SkSL@@YAXAEAUProgram@2@@Z)
          skia.lib(skia.SkSLFindAndDeclareBuiltinVariables.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
          skia.lib(skia.SkNWayCanvas.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
          D:\pigeon\dev\community\skia\skia-test\target\debug\deps\skia_test.exe : fatal error LNK1120: 2 unresolved externals

**Comment by tronical** [comment]
I’ve had similar errors before and updating ton the very latest msvc 2022 patch releases fixed them for me (they often release patches).

**Comment by lencil** [comment]
> I’ve had similar errors before and updating ton the very latest msvc 2022 patch releases fixed them for me (they often release patches).

Thank you, the error lasted before I applied the latest msvc 2022 patch.

**Comment by geniusnut** [comment]
I encounter another error:
```
error LNK2019: ... __std_max_element_1 ....
error LNK2019: ... __std_max_element_2 ....
```
After update Visual Studio Build tools 2022  to 17.7.4, everything is OK.
