### ISSUE TITLE
Windows i686 build error

### ISSUE THREAD

**Issue by lencil** [rust-skia/rust-skia#770]
as #314 mentioned, I placed the src in the same drive as rust toolchains. But still has build error, the log shows that ninja cc cannot find .c file. If I changed it to the absolute path manually it can be found and compiled.

`  ninja: Entering directory `C:\Users\lencil\pigeon\skia-test\target\i686-pc-windows-msvc\debug\build\skia-bindings-6f4ffb0b6fa0dee2\out\skia'

  --- stderr
  Checking for "C:\\Program Files\\LLVM\\bin\\clang-cl.exe"
  ninja: error: '../../../../../../../../../.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.58.0/skia/third_party/externals/zlib/contrib/optimizations/inffast_chunk.c', needed by 'obj/third_party/externals/zlib/contrib/optimizations/zlib_inflate_chunk_simd.inffast_chunk.obj', missing and no known rule to make it
  thread 'main' panicked at '`ninja` returned an error, please check the output for details.', C:\Users\lencil\.cargo\registry\src\github.com-1ecc6299db9ec823\skia-bindings-0.58.0\build_support\skia\config.rs:338:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by pragmatrix** [comment]
Hmm, the file should exist. Sometimes the Skia build script fails to download external dependencies when previous downloads got interrupted.

Try removing the `skia-bindings/skia/third_party/externals` directory and then rebuild.

**Comment by lencil** [comment]
> Hmm, the file should exist. Sometimes the Skia build script fails to download external dependencies when previous downloads got interrupted.
> 
> Try removing the `skia-bindings/skia/third_party/externals` directory and then rebuild.

I've checked the path, I'm sure that the file inffast_chunk.c exactly exists in the path of disk drive. But it's weird the gn cc could not find it. If I modify the path in the .ninja file from ../../../../../../../../../.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.58.0/skia/third_party/externals/zlib/contrib/optimizations/inffast_chunk.c" to absolute path "/Users/lencil/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.58.0/skia/third_party/externals/zlib/contrib/optimizations/inffast_chunk.c", the ninja could touch the file.

**Comment by rustytsuki** [comment]
I found a workround for this. The key is that the gn system and ninja will call GetFullPathNameA() function in windows, this api has a limit path length, your path is too long. 

I found to enable long path support as followed, but not work.

regedit
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled

gpedit.msc
Computer Configuration > Administrative Templates > System > Filesystem > Enable Win32 long paths

so I placed my source code to .cargo/registry/src/github.com-1ecc6299db9ec823, thus the ninja.build generated short path. And it does work!

**Comment by lencil** [comment]
Sounds it like it's the issue of gn/ninja. Ok, thank you guys.

**Comment by pragmatrix** [comment]
Closing. It seems that the issue can be resolved by [enabling long path support](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/) in Windows.

**Comment by DraftedDev** [comment]
I'm still experiencing this issue. I enableed long path support, but still get the error
```
error: unable to create file reference/opt/shaders-msl/comp/argument-buffers-runtime-array-buffer.rich-descriptor.argument.device-argument-buffer.argument-tier-1.msl2.comp: Filename too long
  error: unable to create file reference/shaders-msl/comp/argument-buffers-runtime-array-buffer.rich-descriptor.argument.device-argument-buffer.argument-tier-1.msl2.comp: Filename too long
  error: unable to create file test/subset/data/expected/cff-japanese/SourceHanSans-Regular_subset.drop-hints-desubroutinize-retain-gids.3042,3044,3046,3048,304A,304B.otf: Filename too long
  error: unable to create file test/subset/data/expected/cff-japanese/SourceHanSans-Regular_subset.drop-hints-desubroutinize-retain-gids.3042,3044,3046,73E0,5EA6,8F38.otf: Filename too long
  error: unable to create file test/subset/data/expected/cff-japanese/SourceHanSans-Regular_subset.drop-hints-desubroutinize-retain-gids.660E,6975,73E0,5EA6,8F38,6E05.otf: Filename too long
  error: unable to create file test/subset/data/expected/glyf_partial_instancing/Roboto-Variable.ABC.no-tables-with-item-variations.retain-all-codepoint.wght=200-300-500,wdth=80-90.ttf: Filename too long
  error: unable to create file test/subset/data/expected/glyf_partial_instancing/Roboto-Variable.ABC.no-tables-with-item-variations.retain-all-codepoint.wght=300-600,wdth=85.ttf: Filename too long
  error: unable to create file test/subset/data/expected/glyf_partial_instancing/Roboto-Variable.composite.no-tables-with-item-variations.retain-all-codepoint.wght=200-300-500,wdth=80-90.ttf: Filename too long
  error: unable to create file test/subset/data/expected/glyf_partial_instancing/Roboto-Variable.composite.no-tables-with-item-variations.retain-all-codepoint.wght=300-600,wdth=85.ttf: Filename too long
  ninja: error: '../../../../../../../../../../.cargo/git/checkouts/rust-skia-35c6c5f9d522ea9f/171f443/skia-bindings/skia/third_party/externals/zlib/contrib/optimizations/inffast_chunk.c', needed by 'obj/third_party/externals/zlib/contrib/optimizations/zlib_inflate_chunk_simd.inffast_chunk.obj', missing and no known rule to make it
  thread 'main' panicked at C:\Users\Mikail\.cargo\git\checkouts\rust-skia-35c6c5f9d522ea9f\171f443\skia-bindings\build_support\skia\config.rs:356:5:
  `ninja` returned an error, please check the output for details.
```

I'm using the latest master branch.

**Comment by rustytsuki** [comment]
> I'm still experiencing this issue. I enableed long path support, but still get the error
> 
> ```
> error: unable to create file reference/opt/shaders-msl/comp/argument-buffers-runtime-array-buffer.rich-descriptor.argument.device-argument-buffer.argument-tier-1.msl2.comp: Filename too long
>   error: unable to create file reference/shaders-msl/comp/argument-buffers-runtime-array-buffer.rich-descriptor.argument.device-argument-buffer.argument-tier-1.msl2.comp: Filename too long
>   error: unable to create file test/subset/data/expected/cff-japanese/SourceHanSans-Regular_subset.drop-hints-desubroutinize-retain-gids.3042,3044,3046,3048,304A,304B.otf: Filename too long
>   error: unable to create file test/subset/data/expected/cff-japanese/SourceHanSans-Regular_subset.drop-hints-desubroutinize-retain-gids.3042,3044,3046,73E0,5EA6,8F38.otf: Filename too long
>   error: unable to create file test/subset/data/expected/cff-japanese/SourceHanSans-Regular_subset.drop-hints-desubroutinize-retain-gids.660E,6975,73E0,5EA6,8F38,6E05.otf: Filename too long
>   error: unable to create file test/subset/data/expected/glyf_partial_instancing/Roboto-Variable.ABC.no-tables-with-item-variations.retain-all-codepoint.wght=200-300-500,wdth=80-90.ttf: Filename too long
>   error: unable to create file test/subset/data/expected/glyf_partial_instancing/Roboto-Variable.ABC.no-tables-with-item-variations.retain-all-codepoint.wght=300-600,wdth=85.ttf: Filename too long
>   error: unable to create file test/subset/data/expected/glyf_partial_instancing/Roboto-Variable.composite.no-tables-with-item-variations.retain-all-codepoint.wght=200-300-500,wdth=80-90.ttf: Filename too long
>   error: unable to create file test/subset/data/expected/glyf_partial_instancing/Roboto-Variable.composite.no-tables-with-item-variations.retain-all-codepoint.wght=300-600,wdth=85.ttf: Filename too long
>   ninja: error: '../../../../../../../../../../.cargo/git/checkouts/rust-skia-35c6c5f9d522ea9f/171f443/skia-bindings/skia/third_party/externals/zlib/contrib/optimizations/inffast_chunk.c', needed by 'obj/third_party/externals/zlib/contrib/optimizations/zlib_inflate_chunk_simd.inffast_chunk.obj', missing and no known rule to make it
>   thread 'main' panicked at C:\Users\Mikail\.cargo\git\checkouts\rust-skia-35c6c5f9d522ea9f\171f443\skia-bindings\build_support\skia\config.rs:356:5:
>   `ninja` returned an error, please check the output for details.
> ```
> 
> I'm using the latest master branch.

you can refer to my solution: https://github.com/rustytsuki/skia-binaries
