### ISSUE TITLE
Rendering glitch

### ISSUE THREAD

**Issue by marc2332** [rust-skia/rust-skia#782]
hey! It's me again

I am [updating Freya](https://github.com/marc2332/freya/pull/108) to the v0.60.0, so far so good! Except, I found a problem:

![image](https://user-images.githubusercontent.com/38158676/224555653-4ea8c935-df3b-4a5c-8b89-f82c917a585b.png)
( NOW | BEFORE)

As you can see, the only difference is a slim line in the bottom.

I thought it might have been my fault at first, but then I went and tried with skia-safe manually, and it also happened

![image](https://user-images.githubusercontent.com/38158676/224555750-d38e7a8e-6395-457a-800e-f10788f7b1c7.png)

Maybe I am doing something wrong, I don't know, maybe it's a bug on Skia itself?. Here is the code from above: https://github.com/marc2332/rust-skia-rendering-glitch

Thank you again! 😄

**Comment by pragmatrix** [comment]
Thank you a lot for the report and creating the MRE repo. I am not seeing a line on Windows (2019 MBP) and neither on macOS M2. 🤔 Also checked the Skia bugtracker and found nothing recent that looks related.

**Comment by marc2332** [comment]
> Thank you a lot for the report and creating the MRE repo. I am not seeing a line on Windows (2019 MBP) and neither on macOS M2. 🤔 Also checked the Skia bugtracker and found nothing recent that looks related.

Alright, I have made more testing

https://github.com/marc2332/rust-skia-rendering-glitch/tree/old-glutin

![image](https://user-images.githubusercontent.com/38158676/224575586-1e3bf610-c90d-4142-9ccb-cd21e3e1a0b9.png)


I just tried running skia-safe v0.60.0 with glutin v0.28.0 and... it works! I also tried v0.58.0 with glutin v0.30.0, and it also fails.


Doesn't matter if it's 0.58.0 or 0.60.0, seems like an issue with glutin 0.30.0 🤔 

Perhaps it's a bug on glutin v0.30.0? Or maybe i am doing something wrong?

**Comment by marc2332** [comment]
I have also just tried my repo, Skia 0.60.0 with glutin 0.30.0 on Linux and it works great.

So far, looks like a glutin v0.30.0 + Windows problem, athough you tried and it worked fine 🤔 What windows version do you have? I am using Windows 11

**Comment by pragmatrix** [comment]
> What windows version do you have?

A Windows 10 22H2 with all updates installed.

**Comment by marc2332** [comment]
> > What windows version do you have?
> 
> A Windows 10 22H2 with all updates installed.

I will try with Windows 11 in a different PC later today

**Comment by marc2332** [comment]
> > > What windows version do you have?
> > 
> > 
> > A Windows 10 22H2 with all updates installed.
> 
> I will try with Windows 11 in a different PC later today

I am getting a panic using glutin v0.30.0, with v0.28.0 works perfectly...

![image](https://user-images.githubusercontent.com/38158676/224799994-8eb0cf1b-389a-4a01-b5b6-e5ba78779cf7.png)

😢

**Comment by pragmatrix** [comment]
Hmm, 16 samples sounds strange. A UI library like Freya should probably not want MSAA I guess. Is the selection code similar to the one from skia-safe's gl-example? If so, I think only a configuration with 0 samples (no MSAA) should probably be selected. BTW: Does the gl-example fail also?

You could also try to compile with SKIA_DEBUG=1 from master to see if Skia's tracing facilities spit out more details to the console.

**Comment by marc2332** [comment]
> Hmm, 16 samples sounds strange. A UI library like Freya should probably not want MSAA I guess. Is the selection code similar to the one from skia-safe's gl-example? If so, I think only a configuration with 0 samples (no MSAA) should probably be selected. BTW: Does the gl-example fail also?
> 
> You could also try to compile with SKIA_DEBUG=1 from master to see if Skia's tracing facilities spit out more details to the console.

yep, I basically used the gl-example as reference. The gl-example example probably fails too, https://github.com/marc2332/rust-skia-rendering-glitch is basically a copy and paste of the gl-example, I only modified the drawing.

Okay, I will try the SKIA_DEBUG and without MSAA asap :smile:

**Comment by marc2332** [comment]
> In #783 I've changed the selection algorithm in the gl-window example so that is choses a configuration with the lowest number of samples available.
> 
> BTW: Did a configuration with 0 or 1 samples solve the original rendering glitch, too?

Sadly not, that still happens, but! Only on my main PC, in my other windows (the one that Surface::create_fro... was crashing with samples > 0) doesn't have the weird line 🤔

**Comment by marc2332** [comment]
> BTW: Did a configuration with 0 or 1 samples solve the original rendering glitch, too?

Foget what I said. Looks like I didn't test ir properly! I just tried with the changes you made to the example and it works!

![image](https://user-images.githubusercontent.com/38158676/226211909-cc1f9d97-99cf-45c4-80a6-aa6e61f237fc.png)

2x1! Fixed two bugs with one change 😄
