### ISSUE TITLE
Missing binding to `textlayout::TextStyle::setDecoration` and related methods.

### ISSUE THREAD

**Issue by Tropix126** [rust-skia/rust-skia#809]
Hi there! I'm currently working on [Freya](https://github.com/marc2332/freya)'s styling system, which uses `skia_safe`'s bindings to `SkParagraph` for text rendering, layout, etc...

While implementing a way to customize text decorations, I noticed that there was no method to set a `textlayout::Decoration` on the `TextStyle` struct, even though [there is a method to get the current decoration on the struct](https://rust-skia.github.io/doc/skia_safe/textlayout/type.TextStyle.html#method.decoration). Upon further investigation, it seems like [all methods directly relating to setting text decoration](https://github.com/google/skia/blob/main/modules/skparagraph/include/TextStyle.h#LL211C16-L223C29) are missing from both the skia bindings and `skia_safe`.

Any ideas as to what might be causing this to happen? From looking at git blames, it seems like these methods weren't added especially recently, and we're on what should be the most up-to-date version of the binding.

> Update: I found out about `decoration_mut` from https://github.com/rust-skia/rust-skia/discussions/452, which should work for my purposes, although im still curious.

**Comment by pragmatrix** [comment]
My thought at this point was that the functions pulled into `TextStyle` were redundant while having `decoration_mut`, and it also would introduce more maintenance / code on the Rust side. But now realizing that this diverges from the Skia API and was confusing to you (and presumably even to the maintainers in the future when the APIs in that area change), I think that adding them is a good idea.
