### ISSUE TITLE
Add wrapper for `Paragraph::visit`

### ISSUE THREAD

**Issue by giantpand2000** [rust-skia/rust-skia#827]
Thanks to `skia-safe`, which provides by far the most reliable native text drawing on Rust.

I'm currently having a problem with custom drawing `Paragraph`s and need to access the underlying `RunInfo`s of the Paragraph. Skia provides the `visit` method for this purpose.

Expect it to be available on `skia-safe`.

**Comment by pragmatrix** [comment]
@giantpand2000 It's now in master, release is planned for the next few days, details are in #828. Note that VisitorInfo may be `None` which indicates the end of the line.
