### ISSUE TITLE
No way to know if foreground/background has been set on a TextStyle

### ISSUE THREAD

**Issue by romanzes** [rust-skia/rust-skia#856]
I think this issue was accidentally introduced [here](https://github.com/rust-skia/rust-skia/commit/9bc81b9b69dd2da3ae5a14863451d8bf1b077791#diff-308fa7af28f2b47f86b886a36ab0c36ad9585361070c861bce6e0a6047815f9d). In older versions of `rust-skia`, the users of the API could know whether background or foreground paint has been already set on a text style, because the return type of `TextStyle::foreground()` and `TextStyle::background()` was `Option<&Paint>`. Now the return type is `Paint` and `fHasForeground/fHasBackground` are not exposed either.

**Comment by pragmatrix** [comment]
Yes, you are right, I'm adding the functions `has_foreground()` and `has_background()` to mirror the Skia API. Thank you for reporting this oversight.

**Comment by romanzes** [comment]
Thank you for fixing this!
