### ISSUE TITLE
Add SkData::MakeFromFileName

### ISSUE THREAD

**Issue by Caellian** [rust-skia/rust-skia#879]
I noticed `MakeFromFileName` is marked as todo with note ["not sure if we need this"](https://github.com/rust-skia/rust-skia/blob/d8f340948d751f79468cdff7ee305170baed6b91/skia-safe/src/core/data.rs#L111).

I just wanted to point out that `SkImage::MakeFromEncoded` takes in `SkData` that can be created this way in order to [lazy load](https://skia.googlesource.com/skia/+/2a8c48be4ff65d873d9d5ba65ecef989d82dd0be/site/user/api/SkImage_Reference.md#lazy_image) the image during rendering. Currently, the only way to create a `SkImage` is by loading the bytes up front which can cause worse performance if that image isn't being used for rendering.

To do something like:
```c++
sk_sp<SkData> data(SkData::MakeFromFileName(name));
if (data) {
    auto image = SkImage::MakeFromEncoded(std::move(data));
    if (image) {
        // ... store for later use
    }
}
```
one needs to load the image into a `Vec` using `std::fs::read` and then _copy_ all the data into SkData using `new_copy` (or manage this slice manually/leak memory) which defeats the purpose of `SkImage` being deferred.

I'm new to this library, so I'm sorry if I'm missing something, just thought this usage scenario should be pointed out.

**Comment by pragmatrix** [comment]
Interesting, I did not know that SkData::MakeFromFile (which is invoked by MakeFromFileName) actually is using a memory mapped file. The comment is based on a wrong assumption that they would just invoke MakeFromStream.

**Comment by Caellian** [comment]
I was expecting something along the lines of
```rust
enum Data {
  Loaded {
    // ... data
  },
  LoadLater {
    path: PathBuf,
  }
}
```
instead of mmap. But yeah, the current way does seem to introduce an extra copy of the file as there's no way to read the file directly into library owned memory.
