### ISSUE TITLE
ColorFilter data recovery through ColorFilter::type()

### ISSUE THREAD

**Issue by Caellian** [rust-skia/rust-skia#883]
Skia [`SkColorFilterBase::type()`](https://github.com/google/skia/blob/8e9e168418a01ef4d7e4b2db81971a8c8d59dae9/src/effects/colorfilters/SkColorFilterBase.h#L52) is missing which makes it impossible to retrieve a filter and modify it (e.g. from `Paint::color_filter()`).

There should be a way to access leaf class members of a filter via `Flattenable` interface to allow for use case where a filter of certain kind can be accessed, modified and re-applied to other things.

In C++ it would be valid to reinterpret_cast the pointer to `SkColorFilter` into `SkBlendModeColorFilter` if the `Flattenable` returns the appropriate name in order to access [`SkBlendModeColorFilter::color()`](https://github.com/google/skia/blob/8e9e168418a01ef4d7e4b2db81971a8c8d59dae9/src/effects/colorfilters/SkBlendModeColorFilter.h#L29C16-L29C16) which is part of public API.

This seems tricky because of inheritance as it's difficult to know the layout of leaf classes so I'm guessing it would require some glue.

Ideally, `ColorFilter::type()` should return an enum of custom wrapper structs that call into C bindings accessing these fields at appropriate offsets.

**Comment by pragmatrix** [comment]
> order to access [SkBlendModeColorFilter::color()](https://github.com/google/skia/blob/8e9e168418a01ef4d7e4b2db81971a8c8d59dae9/src/effects/colorfilters/SkBlendModeColorFilter.h#L29C16-L29C16) which is part of public API.

I disagree, but may miss something, `SkBlendModeColorFilter.h` is under `src/` and not accessible through the header files in `include/`, as is `SkColorFilterBase.h`.
