### ISSUE TITLE
Inconsistency: Font::textToGlyphs & Typeface::textToGlyphs

### ISSUE THREAD

**Issue by Caellian** [rust-skia/rust-skia#886]
- `Typeface::textToGlyphs` takes a `C` generic slice that's passed as a pointer to native.
- `Font::textToGlyphs` takes a `u8` slice.

I think `OsString` might be a better fit than either as it's basically a `String` with unknown encoding.

Alternatively, given that `encoding` can be utf8/16/32 or GlyphId, an enum of [different representations](https://github.com/starkat99/widestring-rs) (where discriminant is `TextEncoding`) could replace `text, encoding` arguments for a more rusty interface.

**Comment by pragmatrix** [comment]
Also affected are TextBlob::from_* functions, see #911. These functions might even be unsound because of alignment issues.
