### ISSUE TITLE
Question: canvas.draw_text_blob without textlayout feature

### ISSUE THREAD

**Issue by namse** [rust-skia/rust-skia#911]
Hi.

does `canvas.draw_text_blob` work without feature `textlayout` on windows?

I'm facing the problem that `canvas.draw_text_blob` draw call doesn't draw anything.

**Comment by namse** [comment]
FYI: `canvas.draw_str` with same text, same paint works well.

**Comment by namse** [comment]
Problem fixed. `textlayout` doesn't necessary to run `canvas.draw_text_blob`.
The problem was data type of `GlyphId` and `canvas.draw_text_blob`.

`GlyphId` seems `u16`, and `canvas.draw_text_blob`'s parameter type is `&[u8]`.
I casted GlyphId to usize and re-casted to u8 to pass to draw_text_blob.

The solution is saving GlyphId in it's type and pass glyph ids to `draw_text_blob` with slice casting like below,

```rust
unsafe {
    std::slice::from_raw_parts(
        glyph_ids.as_ptr() as *const u8,
        glyph_ids.len() * std::mem::size_of::<GlyphId>(),
    )
}
```

**Comment by pragmatrix** [comment]
See also: https://github.com/rust-skia/rust-skia/issues/886#issuecomment-1868943743
