### ISSUE TITLE
Support drawAtlas

### ISSUE THREAD

**Issue by triniwiz** [rust-skia/rust-skia#926]
Hi would be nice to add support for `drawAtlas` as I recall seeing a todo for it. 
As for supporting it I think we only need to wrap add one more type `SkRSXform`.

**Comment by pragmatrix** [comment]
Hello @triniwiz! rsxform is [already wrapped](https://github.com/rust-skia/rust-skia/blob/ed6f579784ffad2f9288dc6eb6283f1767c515c7/skia-safe/src/core/rsxform.rs), so wrapping `drawAtlas` should be simple. I am trying to get this ready for the next milestone update.

**Comment by triniwiz** [comment]
@pragmatrix sweet!!!, I only noticed it was wrapped like a day after this issue 😅.
