### ISSUE TITLE
Compiling function #47744:"skcms_private::baseline::exec_stages(skcms_priv..." failed: local count too large

### ISSUE THREAD

**Issue by happylinks** [rust-skia/rust-skia#935]
Hey there,

I'm trying to get the wasm-example working, but any build that I do gets this error in the browser:

<img width="932" alt="image" src="https://github.com/rust-skia/rust-skia/assets/184774/a7c9564e-e82e-47c4-991d-adfad38a318b">

Not sure if I'm building it wrong or if this is broken in the repo.

Would love some help!

**Comment by happylinks** [comment]
@pragmatrix Hey, I noticed you updated the wasm code recently. Any way you can help me with this?
I'm running the make build or make build_release like in the docs, and the build succeeds fine. But when opening the webpage it gives that error ☝️ 
Is it working properly for you and is it just something about my emscripten setup maybe? Or is the example just broken.

**Comment by pragmatrix** [comment]
I've tried the current master on macOS with emsdk 3.1.59 (the `EMSDK` env variable already points to the SDK directory, so the one in the Makefile gets ignored) then in wasm-example/, `make build` and then `make serve`, opening the browser (Chrome latest) at http://localhost:8000/web shows the example: a circle that's movable with the mouse. 

So the master branch _should_ work, at least for the example.

**Comment by happylinks** [comment]
It worked!! I updated from esdk 3.1.53 to 3.1.63 and cleared all my "target" folders, then ran the build again. Not sure why it didn't work before with 3.1.53, but 🤷 
Thanks for the reply!
