### ISSUE TITLE
Variable fonts on Windows are lighter than they should be

### ISSUE THREAD

**Issue by marc2332** [rust-skia/rust-skia#948]
Hey Armin! 👋 

We are not sure whether this is a Skia bug or a rust-skia bug.
But in any case, there seems to be an issue with variable fonts on Windows, they are lighter than they should be. I have made a comparison between Windows 11 and Linux below. I have been told by @geom3trik that it also works just fine in MacOS, so this seems to be only affecting Windows.

[Reproduction example repo](https://github.com/marc2332/rust-skia-variable-fonts-bug).

Windows (unexpected 🤔 ):
1. `NORMAL`:
![image](https://github.com/rust-skia/rust-skia/assets/38158676/0c0cc455-3562-4f15-a296-ef550bad2fc5)

2. `BLACK`:
![image](https://github.com/rust-skia/rust-skia/assets/38158676/c72aacad-19d5-492e-8df5-ed8ce5f1ad04)

Linux or Mac (expected ✅ ):
1. `NORMAL`:
![image](https://github.com/rust-skia/rust-skia/assets/38158676/786d6d16-c3c3-40bb-a5d9-8d7408230157)

2. `BOLD`:
![image](https://github.com/rust-skia/rust-skia/assets/38158676/917c7aee-a30d-42c4-8f10-c821f2fdf0f3)

Perhaps we are doing something wrong? We would appreciate some help 😄 

Thanks!

**Comment by pragmatrix** [comment]
0.71 uses the GDI's font manager by default on Windows, but when I preferred the DirectWrite's FontMgr over the GDI one, the problem seems to disappear. Thanks for providing a minimum reproducible example. That helped a lot.

**Comment by marc2332** [comment]
Thanks! 🦀
