### ISSUE TITLE
Safety issue with `skia_safe::gpu::vk::ImageInfo` struct.

### ISSUE THREAD

**Issue by Greatness7** [rust-skia/rust-skia#953]
Creating this struct is unsafe according to its [implementations](https://rust-skia.github.io/doc/skia_safe/gpu/vk/struct.ImageInfo.html#implementations), which seems reasonable, but since all fields of the struct are public we can easily bypass these methods and create the struct without any unsafe block at all via `ImageInfo { ... }` or `ImageInfo::default()`.

**Comment by pragmatrix** [comment]
I hope that the changes in #955 is what you had in mind. I've made `image` and `alloc` private and added suitable accessors.
