### ISSUE TITLE
Svg text element not rendering

### ISSUE THREAD

**Issue by triniwiz** [rust-skia/rust-skia#960]
Trying to figure out what is preventing the text element from being rendered when using svg, other elements I've tested works thus far. I'm trying to use the cpu route the issue happens on both ios an android. 

Using the same sample as found in the repo, I even tried replacing the `<![CDATA[410]]`

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" height = "256" width = "256">
		<path d="M30,1h40l29,29v40l-29,29h-40l-29-29v-40z" stroke="#000" fill="none"/>
		<path d="M31,3h38l28,28v38l-28,28h-38l-28-28v-38z" fill="#a23"/>
		<text x="50" y="68" font-size="48" fill="#FFF" text-anchor="middle"><![CDATA[410]]></text>
		</svg
```

**Comment by pragmatrix** [comment]
I've tried that test under macOS, and it seems that text rendering does not work beginning with version 0.70 of skia-safe (Skia Milestone 121). 0.69 seems to render the text just fine.

**Comment by triniwiz** [comment]
@pragmatrix thanks for the confirmation
