### ISSUE TITLE
SIGSEGV  Error in MacOS when  measuring SkParagraphs with emojis

### ISSUE THREAD

**Issue by marc2332** [rust-skia/rust-skia#984]
Hey! I was just adding some unit tests to https://github.com/marc2332/freya/pull/622 and started getting some crashes only in MacOS (maybe Linux too), but definitely not in Windows. I narrowed it down to a skparagraph being measured (`layout()`) with emojies in the text, so:

Works:

```rs
#[test]
fn skia_not_crash_crash_macos() {
    let mut font_collection = FontCollection::new();
    font_collection.set_dynamic_font_manager(FontMgr::default());
    let mut p = ParagraphBuilder::new(&ParagraphStyle::new(), font_collection);
    p.add_text("test test");
    let mut paragraph = p.build();
    paragraph.layout(200.);
}
```

Doesn't work:

```rs
#[test]
fn skia_crash_macos() {
    let mut font_collection = FontCollection::new();
    font_collection.set_dynamic_font_manager(FontMgr::default());
    let mut p = ParagraphBuilder::new(&ParagraphStyle::new(), font_collection);
    p.add_text("👋test test 🦀");
    let mut paragraph = p.build();
    paragraph.layout(200.);
}
```

![image](https://github.com/rust-skia/rust-skia/assets/38158676/63b889e5-90d0-42e1-be44-c9c04f0ecbac)

I don't know if it's related to being executed in the CI or not as I don't have a Mac device.

Any idea?

**Comment by tronical** [comment]
I think that this might be https://github.com/google/skia/pull/162#issuecomment-1968603073

**Comment by marc2332** [comment]
> I think that this might be [google/skia#162 (comment)](https://github.com/google/skia/pull/162#issuecomment-1968603073)

Whoah! Nice find Simon, that's indeed the issue. Freya's headless testing runner was not specifying a default FontMgr, I just made it do so and it worked ✨ 

Should I close this or it's better to leave it open until your fix has been merged and rust-skia updated the bindings?

**Comment by pragmatrix** [comment]
@marc2332 Leave it open, we are shortly before the Milestone 126 update release, I'll cherry-pick Simon's patch.
