### ISSUE TITLE
build windows11x64 failed

### ISSUE THREAD

**Issue by JiuXin303** [rust-skia/rust-skia#988]
`error: failed to run custom build command for `skia-bindings v0.72.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `(no show my path,has my info)\target\debug\build\skia-bindings-b76f6dee6a231291\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-env-changed=SKIA_DEBUG
  HOST: x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.72.0/44350c3dcc5ddd5cc9ae-x86_64-pc-windows-msvc-d3d-gl-textlayout-vulkan
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.72.0/skia-binaries-44350c3dcc5ddd5cc9ae-x86_64-pc-windows-msvc-d3d-gl-textlayout-vulkan.tar.gz
  DOWNLOAD AND INSTALL FAILED: curl error code: Some(28)
  curl stderr: Ok("")
  STARTING A FULL BUILD
  cargo:rerun-if-env-changed=CLANGCC
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CLANGCXX
  cargo:rerun-if-env-changed=CXX
  HOST: x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  HOST: x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=SDKTARGETSYSROOT
  cargo:rerun-if-env-changed=SDKROOT
  HOST: x86_64-pc-windows-msvc
  HOST: x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=VCINSTALLDIR
  cargo:rerun-if-env-changed=LLVM_HOME
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Python 3 found: "python"
  Synchronizing Skia dependencies
  DOWNLOADING: https://codeload.github.com/rust-skia/skia/tar.gz/m123-0.71.2

  --- stderr
  Checking for "D:\\clang+llvm-msvc\\bin\\clang-cl.exe"
  thread 'main' panicked at (no show my path,has my info)\.cargo\registry\src\index.crates.io-6f17d22bba15001f\skia-bindings-0.72.0\build_support\binary_cache\download.rs:93:43:
  called `Result::unwrap()` on an `Err` value: Custom { kind: Uncategorized, error: TarError { desc: "failed to unpack `(no show my path,has my info)\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\skia-bindings-0.72.0\\skia-m123-0.71.2\\bazel\\external\\expat\\config\\expat_config.h`", io: Custom { kind: Uncategorized, error: "客户端没有所需的特权。 (os error 1314) when symlinking ../../../../third_party/expat/include/expat_config/expat_config.h to (no show my path,has my info)\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\skia-bindings-0.72.0\\skia-m123-0.71.2\\bazel\\external\\expat\\config\\expat_config.h" } } }
  stack backtrace:
     0:     0x7ff6893e0fda - std::backtrace_rs::backtrace::dbghelp64::trace
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:99
     1:     0x7ff6893e0fda - std::backtrace_rs::backtrace::trace_unsynchronized
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
     2:     0x7ff6893e0fda - std::sys_common::backtrace::_print_fmt
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common\backtrace.rs:68
     3:     0x7ff6893e0fda - std::sys_common::backtrace::_print::impl$0::fmt
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common\backtrace.rs:44
     4:     0x7ff689404c8b - core::fmt::rt::Argument::fmt
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\fmt\rt.rs:142    
     5:     0x7ff689404c8b - core::fmt::write
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\fmt\mod.rs:1153  
     6:     0x7ff6893dbe21 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\io\mod.rs:1843    
     7:     0x7ff6893e0dc6 - std::sys_common::backtrace::print
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common\backtrace.rs:34
     8:     0x7ff6893e349f - std::panicking::default_hook::closure$1
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:272  
     9:     0x7ff6893e3137 - std::panicking::default_hook
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:292  
    10:     0x7ff6893e39dd - std::panicking::rust_panic_with_hook
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:779  
    11:     0x7ff6893e3899 - std::panicking::begin_panic_handler::closure$0
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:657  
    12:     0x7ff6893e18e9 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common\backtrace.rs:171
    13:     0x7ff6893e3556 - std::panicking::begin_panic_handler
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645  
    14:     0x7ff68940e1d7 - core::panicking::panic_fmt
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72  
    15:     0x7ff68940e7b3 - core::result::unwrap_failed
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\result.rs:1654   
    16:     0x7ff688bbd4a2 - build_script_build::build_support::binary_cache::download::resolve_dependencies::h03c316eebdcdf708
    17:     0x7ff688bbc8ba - build_script_build::build_support::binary_cache::download::resolve_dependencies::h03c316eebdcdf708
    18:     0x7ff688b8ee18 - build_script_build::build_support::skia::config::build::h27997e95adf41e34
    19:     0x7ff688bc1581 - build_script_build::build_support::skia_bindgen::rewrite::capture::{{closure}}::ha028357fe39f9f09
    20:     0x7ff688bc0cac - build_script_build::build_support::skia_bindgen::rewrite::capture::{{closure}}::ha028357fe39f9f09
    21:     0x7ff688b91376 - core::ops::function::FnOnce::call_once::h7399fd114eb109db
    22:     0x7ff688b9c809 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb6d13c918a92c7bb
    23:     0x7ff688ba7e3c - std::rt::lang_start::{{closure}}::ha11612fb0548367b
    24:     0x7ff6893d6ac2 - std::rt::lang_start_internal
                                 at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\rt.rs:148
    25:     0x7ff688ba7e17 - std::rt::lang_start::h67eb392371f3cb95
    26:     0x7ff688bc1ae9 - main
    27:     0x7ff68940b630 - invoke_main
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    28:     0x7ff68940b630 - __scrt_common_main_seh
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    29:     0x7ff9c037257d - BaseThreadInitThunk
    30:     0x7ff9c1daaa48 - RtlUserThreadStart`

# It seems that curl does not have the permission to decompress the compressed file. May I ask if the source code was cloned from the official website? If so, can it be downloaded using git instead of curl?

**Comment by tronical** [comment]
I think the error is that your user account on Windows does not have permission to create symbolic links. This is required for the build to succeed.

**Comment by JiuXin303** [comment]
> 我认为错误是您在 Windows 上的用户帐户无权创建符号链接。这是生成成功所必需的。
<img width="761" alt="无标题" src="https://github.com/rust-skia/rust-skia/assets/50227375/e4adcc44-8615-4140-9498-bb8db47b3ab6">

# This file cannot be unzipped from my computer, I need to use git, I can also download them manually, but I don't know how to tell them that I have downloaded them.
# Can you tell me?

**Comment by tronical** [comment]
You need to enable support for symlinks for you user in Windows. This article from the Windows blog - that's a little outdated - provides some background: https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/ . The easiest way to enable symlinks support is to enable developer mode in your Windows system settings.

**Comment by JiuXin303** [comment]
> 您需要在 Windows 中为用户启用对符号链接的支持。这篇来自 Windows 博客的文章 - 有点过时了 - 提供了一些背景信息：https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/ .启用符号链接支持的最简单方法是在 Windows 系统设置中启用开发人员模式。

Thank!
